# Pandas Practice

## Imports

As always, we begin with some imports.

In [10]:
import pandas as pd
from pandas import DataFrame
from pandas import Series, DataFrame
import glob
from pathlib import Path

import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

## Corpus

For this notebook, we'll return to our corpus of _New York Times_ obituaries.

In [2]:
# collect filepaths as files
directory = "../docs/NYT-Obituaries/"
files = glob.glob(f"{directory}/*.txt")
files

['../docs/NYT-Obituaries/1945-Adolf-Hitler.txt',
 '../docs/NYT-Obituaries/1915-F-W-Taylor.txt',
 '../docs/NYT-Obituaries/1975-Chiang-Kai-shek.txt',
 '../docs/NYT-Obituaries/1984-Ethel-Merman.txt',
 '../docs/NYT-Obituaries/1953-Jim-Thorpe.txt',
 '../docs/NYT-Obituaries/1964-Nella-Larsen.txt',
 '../docs/NYT-Obituaries/1955-Margaret-Abbott.txt',
 '../docs/NYT-Obituaries/1984-Lillian-Hellman.txt',
 '../docs/NYT-Obituaries/1959-Cecil-De-Mille.txt',
 '../docs/NYT-Obituaries/1928-Mabel-Craty.txt',
 '../docs/NYT-Obituaries/1973-Eddie-Rickenbacker.txt',
 '../docs/NYT-Obituaries/1989-Ferdinand-Marcos.txt',
 '../docs/NYT-Obituaries/1991-Martha-Graham.txt',
 '../docs/NYT-Obituaries/1997-Deng-Xiaoping.txt',
 '../docs/NYT-Obituaries/1938-George-E-Hale.txt',
 '../docs/NYT-Obituaries/1885-Ulysses-Grant.txt',
 '../docs/NYT-Obituaries/1909-Sarah-Orne-Jewett.txt',
 '../docs/NYT-Obituaries/1957-Christian-Dior.txt',
 '../docs/NYT-Obituaries/1987-Clare-Boothe-Luce.txt',
 '../docs/NYT-Obituaries/1976-Jacques-Monod.txt',
 '../docs/NYT-Obituaries/1954-Getulio-Vargas.txt',
 '../docs/NYT-Obituaries/1979-Stan-Kenton.txt',
 '../docs/NYT-Obituaries/1990-Leonard-Bernstein.txt',
 '../docs/NYT-Obituaries/1972-Jackie-Robinson.txt',
 '../docs/NYT-Obituaries/1998-Fred-W-Friendly.txt',
 '../docs/NYT-Obituaries/1991-Leo-Durocher.txt',
 '../docs/NYT-Obituaries/1915-B-T-Washington.txt',
 '../docs/NYT-Obituaries/1997-James-Stewart.txt',
 '../docs/NYT-Obituaries/1981-Joe-Louis.txt',
 '../docs/NYT-Obituaries/1983-Muddy-Waters.txt',
 '../docs/NYT-Obituaries/1942-George-M-Cohan.txt',
 '../docs/NYT-Obituaries/1989-Samuel-Beckett.txt',
 '../docs/NYT-Obituaries/1962-Marilyn-Monroe.txt',
 '../docs/NYT-Obituaries/2000-Charles-M-Schulz.txt',
 '../docs/NYT-Obituaries/1967-Gregory-Pincus.txt',
 '../docs/NYT-Obituaries/1894-R-L-Stevenson.txt',
 '../docs/NYT-Obituaries/1978-Bruce-Catton.txt',
 '../docs/NYT-Obituaries/1982-Arthur-Rubinstein.txt',
 '../docs/NYT-Obituaries/1875-Andrew-Johnson.txt',
 '../docs/NYT-Obituaries/1974-Charles-Lindbergh.txt',
 '../docs/NYT-Obituaries/1964-Rachel-Carson.txt',
 '../docs/NYT-Obituaries/1953-Marjorie-Rawlings.txt',
 '../docs/NYT-Obituaries/1973-Otto-Klemperer.txt',
 '../docs/NYT-Obituaries/1963-Sylvia-Plath.txt',
 '../docs/NYT-Obituaries/1956-Charles-Merrill.txt',
 '../docs/NYT-Obituaries/1966-Lenny-Bruce.txt',
 '../docs/NYT-Obituaries/1908-Cleveland.txt',
 '../docs/NYT-Obituaries/1982-Anna-Freud.txt',
 '../docs/NYT-Obituaries/1941-Frank-Conrad.txt',
 '../docs/NYT-Obituaries/1966-Alfred-P-Sloan-Jr.txt',
 '../docs/NYT-Obituaries/1960-Beno-Gutenberg.txt',
 '../docs/NYT-Obituaries/1976-J-Paul-Getty.txt',
 '../docs/NYT-Obituaries/1891-P-T-Barnum.txt',
 '../docs/NYT-Obituaries/1901-Queen-Victoria.txt',
 '../docs/NYT-Obituaries/1970-Erich-Maria-Remarque.txt',
 '../docs/NYT-Obituaries/1989-August-A-Busch-Jr.txt',
 '../docs/NYT-Obituaries/1992-John-Cage.txt',
 '../docs/NYT-Obituaries/1994-Erik-Erikson.txt',
 '../docs/NYT-Obituaries/1990-Erte.txt',
 '../docs/NYT-Obituaries/1966-Chester-Nimitz.txt',
 '../docs/NYT-Obituaries/1954-Enrico-Fermi.txt',
 '../docs/NYT-Obituaries/1961-Primitive-Artist.txt',
 '../docs/NYT-Obituaries/1945-Bela-Bartok.txt',
 '../docs/NYT-Obituaries/1978-Pope-Paul-VI.txt',
 '../docs/NYT-Obituaries/1965-Martin-Buber.txt',
 '../docs/NYT-Obituaries/1971-Diane-Arbus.txt',
 '../docs/NYT-Obituaries/1973-Lyndon-Johnson.txt',
 '../docs/NYT-Obituaries/1998-Bob-Kane.txt',
 '../docs/NYT-Obituaries/1969-Judy-Garland.txt',
 '../docs/NYT-Obituaries/1959-Frank-Lloyd-Wright.txt',
 '../docs/NYT-Obituaries/1995-Ginger-Rogers.txt',
 '../docs/NYT-Obituaries/1920-Marlene-Dietrich.txt',
 '../docs/NYT-Obituaries/1998-Alan-B-Shepard-Jr.txt',
 '../docs/NYT-Obituaries/1971-Khrushchev.txt',
 '../docs/NYT-Obituaries/1935-Justice-Holmes.txt',
 '../docs/NYT-Obituaries/1969-David-Eisenhower.txt',
 '../docs/NYT-Obituaries/1992-Marsha-P-Johnson.txt',
 '../docs/NYT-Obituaries/1914-Alfred-Thayer-Mahan.txt',
 '../docs/NYT-Obituaries/1965-Branch-Rickey.txt',
 '../docs/NYT-Obituaries/1965-Albert-Schweitzer.txt',
 '../docs/NYT-Obituaries/1992-Isaac-Asimov.txt',
 '../docs/NYT-Obituaries/1989-William-B-Shockley.txt',
 '../docs/NYT-Obituaries/1910-William-James.txt',
 '../docs/NYT-Obituaries/1951-Fanny-Brice.txt',
 '../docs/NYT-Obituaries/1916-Jack-London.txt',
 '../docs/NYT-Obituaries/1947-Al-Capone.txt',
 '../docs/NYT-Obituaries/1989-Lucille-Ball.txt',
 '../docs/NYT-Obituaries/1980-Jean-Paul-Sartre.txt',
 '../docs/NYT-Obituaries/1969-Sonja-Henie.txt',
 '../docs/NYT-Obituaries/1976-Adolph-Zukor.txt',
 '../docs/NYT-Obituaries/1959-John-Dulles.txt',
 '../docs/NYT-Obituaries/1980-Alfred-Hitchcock.txt',
 '../docs/NYT-Obituaries/1901-Benjamin-Harrison.txt',
 '../docs/NYT-Obituaries/1994-Richard-Nixon.txt',
 '../docs/NYT-Obituaries/1917-Hilaire-G-E-Degas.txt',
 '../docs/NYT-Obituaries/1987-James-Baldwin.txt',
 '../docs/NYT-Obituaries/1941-Virginia-Woolf.txt',
 '../docs/NYT-Obituaries/1922-Alexander-Graham-Bell.txt',
 '../docs/NYT-Obituaries/1907-Qiu-Jin.txt',
 '../docs/NYT-Obituaries/1895-Fred-Douglass.txt',
 '../docs/NYT-Obituaries/1971-Florence-Blanchfield.txt',
 '../docs/NYT-Obituaries/1984-Ray-A-Kroc.txt',
 '../docs/NYT-Obituaries/1947-Fiorello-La-Guardia.txt',
 '../docs/NYT-Obituaries/1988-Louis-L-Amour.txt',
 '../docs/NYT-Obituaries/1902-Elizabeth-Cady-Stanton.txt',
 '../docs/NYT-Obituaries/1965-Shirley-Jackson.txt',
 '../docs/NYT-Obituaries/1979-John-Wayne.txt',
 '../docs/NYT-Obituaries/1994-Thomas-P-O-Neill-Jr.txt',
 '../docs/NYT-Obituaries/1982-Thelonious-Monk.txt',
 '../docs/NYT-Obituaries/1919-C-J-Walker.txt',
 '../docs/NYT-Obituaries/1954-Liberty-H-Bailey.txt',
 '../docs/NYT-Obituaries/1977-Dash-Ended.txt',
 '../docs/NYT-Obituaries/1936-Maxim-Gorky.txt',
 '../docs/NYT-Obituaries/2000-Pierre-Trudeau.txt',
 '../docs/NYT-Obituaries/1976-Mao-Tse-Tung.txt',
 '../docs/NYT-Obituaries/1955-Walter-White.txt',
 '../docs/NYT-Obituaries/1930-Conan-Doyle.txt',
 '../docs/NYT-Obituaries/1995-Jonas-Salk.txt',
 '../docs/NYT-Obituaries/1949-Mitchell.txt',
 '../docs/NYT-Obituaries/1951-Henrietta-Lacks.txt',
 '../docs/NYT-Obituaries/1903-James-M-N-Whistler.txt',
 '../docs/NYT-Obituaries/1950-A-J-Dempster.txt',
 '../docs/NYT-Obituaries/1937-Edith-Wharton.txt',
 '../docs/NYT-Obituaries/1935-Jane-Addams.txt',
 '../docs/NYT-Obituaries/1941-James-Joyce.txt',
 '../docs/NYT-Obituaries/1952-John-Dewey.txt',
 '../docs/NYT-Obituaries/1940-Marcus-Garvey.txt',
 '../docs/NYT-Obituaries/1971-Louis-Armstrong.txt',
 '../docs/NYT-Obituaries/1923-Warren-Harding.txt',
 '../docs/NYT-Obituaries/1937-John-Rockefeller.txt',
 '../docs/NYT-Obituaries/2000-Elliot-Richardson.txt',
 '../docs/NYT-Obituaries/1972-J-Edgar-Hoover.txt',
 '../docs/NYT-Obituaries/1975-Franco.txt',
 '../docs/NYT-Obituaries/1973-Jeanette-Rankin.txt',
 '../docs/NYT-Obituaries/1888-Louisa-M-Alcott.txt',
 '../docs/NYT-Obituaries/1977-Charles-Chaplin.txt',
 '../docs/NYT-Obituaries/1990-Ralph-David-Abernathy.txt',
 '../docs/NYT-Obituaries/1946-Lord-Keynes.txt',
 '../docs/NYT-Obituaries/1996-Gene-Kelly.txt',
 '../docs/NYT-Obituaries/1973-Roberto-Clemente.txt',
 '../docs/NYT-Obituaries/1986-Georgia-O-Keeffe.txt',
 '../docs/NYT-Obituaries/1990-Rex-Harrison.txt',
 '../docs/NYT-Obituaries/1916-Martian-Theory.txt',
 '../docs/NYT-Obituaries/1961-Ernest-Hemingway.txt',
 '../docs/NYT-Obituaries/1978-Margaret-Mead.txt',
 '../docs/NYT-Obituaries/1982-Ingrid-Bergman.txt',
 '../docs/NYT-Obituaries/1946-C-E-M-Clung.txt',
 '../docs/NYT-Obituaries/1977-Maria-Callas.txt',
 '../docs/NYT-Obituaries/1952-Eva-Peron.txt',
 '../docs/NYT-Obituaries/1961-Emily-Balch.txt',
 '../docs/NYT-Obituaries/1979-Arthur-Fiedler.txt',
 '../docs/NYT-Obituaries/1896-Harriet-Beecher-Stowe.txt',
 '../docs/NYT-Obituaries/1989-Andrei-Sakharov.txt',
 '../docs/NYT-Obituaries/1939-W-B-Yeats.txt',
 '../docs/NYT-Obituaries/1961-Hammarskjold.txt',
 '../docs/NYT-Obituaries/1969-Madhubala.txt',
 '../docs/NYT-Obituaries/1970-Edouard-Daladier.txt',
 '../docs/NYT-Obituaries/1988-John-Houseman.txt',
 '../docs/NYT-Obituaries/1992-William-Shawn.txt',
 '../docs/NYT-Obituaries/1950-Edna-St-V-Millay.txt',
 '../docs/NYT-Obituaries/1989-Claude-Pepper.txt',
 '../docs/NYT-Obituaries/1929-Marie-Curie.txt',
 '../docs/NYT-Obituaries/1972-The-Duke-of-Windsor.txt',
 '../docs/NYT-Obituaries/1984-Count-Basie.txt',
 '../docs/NYT-Obituaries/1998-Helen-Moody.txt',
 '../docs/NYT-Obituaries/1936-Anne-Macy.txt',
 '../docs/NYT-Obituaries/1900-Nietzsche.txt',
 '../docs/NYT-Obituaries/1880-Lucretia-Mott.txt',
 '../docs/NYT-Obituaries/1967-J-Robert-Oppenheimer.txt',
 '../docs/NYT-Obituaries/1984-Richard-Burton.txt',
 '../docs/NYT-Obituaries/1964-Sean-O-Casey.txt',
 '../docs/NYT-Obituaries/1931-Thomas-Edison.txt',
 '../docs/NYT-Obituaries/1971-Bobby-Jones.txt',
 '../docs/NYT-Obituaries/1914-John-P-Holland.txt',
 '../docs/NYT-Obituaries/1995-George-Abbott.txt',
 '../docs/NYT-Obituaries/1950-Henry-L-Stimson.txt',
 '../docs/NYT-Obituaries/1955-Dale-Carnegie.txt',
 '../docs/NYT-Obituaries/1934-T-A-Watson.txt',
 '../docs/NYT-Obituaries/1968-Martin-Luther-King-Jr.txt',
 '../docs/NYT-Obituaries/1933-Louis-C-Tiffany.txt',
 '../docs/NYT-Obituaries/1909-Geronimo.txt',
 '../docs/NYT-Obituaries/1952-Charles-Spaulding.txt',
 '../docs/NYT-Obituaries/1922-Nellie-Bly.txt',
 '../docs/NYT-Obituaries/1955-Cy-Young.txt',
 '../docs/NYT-Obituaries/1993-Arthur-Ashe.txt',
 '../docs/NYT-Obituaries/1986-Bernard-Malamud.txt',
 '../docs/NYT-Obituaries/1939-Howard-Carter.txt',
 '../docs/NYT-Obituaries/1994-Linus-C-Pauling.txt',
 '../docs/NYT-Obituaries/1967-Langston-Hughes.txt',
 '../docs/NYT-Obituaries/1948-Mohandas-K-Gandhi.txt',
 '../docs/NYT-Obituaries/1931-Melvil-Dewey.txt',
 '../docs/NYT-Obituaries/1969-Everett-Dirksen.txt',
 '../docs/NYT-Obituaries/1968-Helen-Keller.txt',
 '../docs/NYT-Obituaries/1992-Alex-Haley.txt',
 '../docs/NYT-Obituaries/1953-Eugene-O-Neill.txt',
 '../docs/NYT-Obituaries/1981-Anwar-el-Sadat.txt',
 '../docs/NYT-Obituaries/1937-Maurice-Ravel.txt',
 '../docs/NYT-Obituaries/1966-Margaret-Sanger.txt',
 '../docs/NYT-Obituaries/1989-I-F-Stone.txt',
 '../docs/NYT-Obituaries/1943-J-H-Kellogg.txt',
 '../docs/NYT-Obituaries/1985-Roger-Maris.txt',
 '../docs/NYT-Obituaries/1972-Mahalia-Jackson.txt',
 '../docs/NYT-Obituaries/1990-Greta-Garbo.txt',
 '../docs/NYT-Obituaries/1998-Benjamin-Spock.txt',
 '../docs/NYT-Obituaries/1994-Jessica-Tandy.txt',
 '../docs/NYT-Obituaries/1979-Richard-Rodgers.txt',
 '../docs/NYT-Obituaries/1958-W-C-Handy.txt',
 '../docs/NYT-Obituaries/1974-Ed-Sullivan.txt',
 '../docs/NYT-Obituaries/1989-Hirohito.txt',
 '../docs/NYT-Obituaries/1933-Calvin-Coolidge.txt',
 '../docs/NYT-Obituaries/1969-Ho-Chi-Minh.txt',
 '../docs/NYT-Obituaries/1987-John-Huston.txt',
 '../docs/NYT-Obituaries/1984-Johnny-Weissmuller.txt',
 '../docs/NYT-Obituaries/1969-Maureen-Connolly.txt',
 '../docs/NYT-Obituaries/1968-Yuri-Gagarin.txt',
 '../docs/NYT-Obituaries/1991-Peggy-Ashcroft.txt',
 '../docs/NYT-Obituaries/1979-A-Philip-Randolph.txt',
 '../docs/NYT-Obituaries/1946-Gertrude-Stein.txt',
 '../docs/NYT-Obituaries/1993-Thurgood-Marshall.txt',
 '../docs/NYT-Obituaries/1887-Emma-Lazarus.txt',
 '../docs/NYT-Obituaries/1986-James-Cagney.txt',
 '../docs/NYT-Obituaries/1976-Richard-Daley.txt',
 '../docs/NYT-Obituaries/1977-Joan-Crawford.txt',
 '../docs/NYT-Obituaries/1971-Hugo-Black.txt',
 '../docs/NYT-Obituaries/1954-Henri-Matisse.txt',
 '../docs/NYT-Obituaries/1906-Susan-B-Anthony.txt',
 '../docs/NYT-Obituaries/1990-Sammy-Davis-Jr.txt',
 '../docs/NYT-Obituaries/1914-John-Muir.txt',
 '../docs/NYT-Obituaries/1954-Anne-O-Hare-McCormick.txt',
 '../docs/NYT-Obituaries/1986-Kate-Smith.txt',
 '../docs/NYT-Obituaries/1919-Anna-H-Shaw.txt',
 '../docs/NYT-Obituaries/1980-Jean-Piaget.txt',
 '../docs/NYT-Obituaries/1966-Buster-Keaton.txt',
 '../docs/NYT-Obituaries/1997-Allen-Ginsberg.txt',
 '../docs/NYT-Obituaries/1991-Miles-Davis.txt',
 '../docs/NYT-Obituaries/1982-Satchel-Paige.txt',
 '../docs/NYT-Obituaries/1931-Ida-B-Wells.txt',
 '../docs/NYT-Obituaries/1967-Henry-R-Luce.txt',
 '../docs/NYT-Obituaries/1984-Ansel-Adams.txt',
 '../docs/NYT-Obituaries/1945-Ernie-Pyle.txt',
 '../docs/NYT-Obituaries/1952-Chaim-Weizmann.txt',
 '../docs/NYT-Obituaries/1973-Nancy-Mitford.txt',
 '../docs/NYT-Obituaries/1852-Ada-Lovelace.txt',
 '../docs/NYT-Obituaries/1996-Timothy-Leary.txt',
 '../docs/NYT-Obituaries/1919-Carnegie-Started.txt',
 '../docs/NYT-Obituaries/1989-Andrei-A-Gromyko.txt',
 '../docs/NYT-Obituaries/1965-David-O-Selznick.txt',
 '../docs/NYT-Obituaries/1870-Robert-E-Lee.txt',
 '../docs/NYT-Obituaries/1968-Robert-Francis-Kennedy.txt',
 '../docs/NYT-Obituaries/1900-Stephen-Crane.txt',
 '../docs/NYT-Obituaries/1936-John-W-Heisman.txt',
 '../docs/NYT-Obituaries/1998-Maureen-O-Sullivan.txt',
 '../docs/NYT-Obituaries/1953-Joseph-Stalin.txt',
 '../docs/NYT-Obituaries/1944-Alfred-E-Smith.txt',
 '../docs/NYT-Obituaries/1910-Tolstoy.txt',
 '../docs/NYT-Obituaries/1964-Cole-Porter.txt',
 '../docs/NYT-Obituaries/1983-Jack-Dempsey.txt',
 '../docs/NYT-Obituaries/1975-Haile-Selassie.txt',
 '../docs/NYT-Obituaries/1882-Charles-Darwin.txt',
 '../docs/NYT-Obituaries/1903-Emily-Warren-Roebling.txt',
 '../docs/NYT-Obituaries/1962-Eleanor-Roosevelt.txt',
 '../docs/NYT-Obituaries/1926-Harry-Houdini.txt',
 '../docs/NYT-Obituaries/1955-Albert-Einstein.txt',
 '../docs/NYT-Obituaries/1971-Coco-Chanel.txt',
 '../docs/NYT-Obituaries/1959-Billie-Holiday.txt',
 '../docs/NYT-Obituaries/1969-Coleman-Hawkins.txt',
 '../docs/NYT-Obituaries/1954-Frida-Kahlo.txt',
 '../docs/NYT-Obituaries/1911-Joseph-Pulitzer.txt',
 '../docs/NYT-Obituaries/1993-Carlos-Montoya.txt',
 '../docs/NYT-Obituaries/1947-Max-Planck.txt',
 '../docs/NYT-Obituaries/1985-Orson-Welles.txt',
 '../docs/NYT-Obituaries/1974-Earl-Warren.txt',
 '../docs/NYT-Obituaries/1971-Ralph-Bunche.txt',
 '../docs/NYT-Obituaries/1999-Hassan-II.txt',
 '../docs/NYT-Obituaries/1931-Knute-Rocke.txt',
 '../docs/NYT-Obituaries/1998-Theodore-Schultz.txt',
 '../docs/NYT-Obituaries/1960-Boris-Pasternak.txt',
 '../docs/NYT-Obituaries/1927-Victoria-Martin.txt',
 '../docs/NYT-Obituaries/1943-George-Washington-Carver.txt',
 '../docs/NYT-Obituaries/1956-Thomas-J-Watson-Sr.txt',
 '../docs/NYT-Obituaries/1947-Henry-Ford.txt',
 '../docs/NYT-Obituaries/1953-Fred-Vinson.txt',
 '../docs/NYT-Obituaries/1982-Leonid-Brezhnev.txt',
 '../docs/NYT-Obituaries/1999-King-Hussein.txt',
 '../docs/NYT-Obituaries/1930-Elmer-Sperry.txt',
 '../docs/NYT-Obituaries/1985-E-B-White.txt',
 '../docs/NYT-Obituaries/1959-Ethel-Barrymore.txt',
 '../docs/NYT-Obituaries/1986-Benny-Goodman.txt',
 '../docs/NYT-Obituaries/1963-W-E-B-DuBois.txt',
 '../docs/NYT-Obituaries/1975-Elijah-Muhammad.txt',
 '../docs/NYT-Obituaries/1973-Pablo-Picasso.txt',
 '../docs/NYT-Obituaries/1993-Federico-Fellini.txt',
 '../docs/NYT-Obituaries/1945-Harry-S-Truman.txt',
 '../docs/NYT-Obituaries/1970-De-Gaulle-Rallied.txt',
 '../docs/NYT-Obituaries/1995-Alfred-Eisenstaedt.txt',
 '../docs/NYT-Obituaries/1999-Iris-Murdoch.txt',
 '../docs/NYT-Obituaries/1987-Alf-Landon.txt',
 '../docs/NYT-Obituaries/1998-Bella-Abzug.txt',
 '../docs/NYT-Obituaries/1940-Scott-Fitzgerald.txt',
 '../docs/NYT-Obituaries/1989-Vladimir-Horowitz.txt',
 '../docs/NYT-Obituaries/1969-Mies-van-der-Rohe.txt',
 '../docs/NYT-Obituaries/1944-Ida-M-Tarbell.txt',
 '../docs/NYT-Obituaries/1948-John-Pershing.txt',
 '../docs/NYT-Obituaries/1938-Clarence-Darrow.txt',
 '../docs/NYT-Obituaries/1987-Primo-Levi.txt',
 '../docs/NYT-Obituaries/1971-Igor-Stravinsky.txt',
 '../docs/NYT-Obituaries/1945-George-Patton.txt',
 '../docs/NYT-Obituaries/1930-William-Howard-Taft.txt',
 '../docs/NYT-Obituaries/1935-Will-Rogers.txt',
 '../docs/NYT-Obituaries/1992-Shirley-Booth.txt',
 '../docs/NYT-Obituaries/1994-Jacqueline-Kennedy.txt',
 '../docs/NYT-Obituaries/1933-Ring-Lardner.txt',
 '../docs/NYT-Obituaries/1974-Sylvia-Plath.txt',
 '../docs/NYT-Obituaries/1945-FDR.txt',
 '../docs/NYT-Obituaries/1995-Yitzhak-Rabin.txt',
 '../docs/NYT-Obituaries/1960-Emily-Post.txt',
 '../docs/NYT-Obituaries/1984-Truman-Capote.txt',
 '../docs/NYT-Obituaries/1968-Upton-Sinclair.txt',
 '../docs/NYT-Obituaries/1994-Jan-Tinbergen.txt',
 '../docs/NYT-Obituaries/1957-Gerard-Swope.txt',
 '../docs/NYT-Obituaries/1993-Albert-Sabin.txt',
 '../docs/NYT-Obituaries/1955-Thomas-Mann.txt',
 '../docs/NYT-Obituaries/1991-Dr-Seuss.txt',
 '../docs/NYT-Obituaries/1877-Bedford-Forrest.txt',
 '../docs/NYT-Obituaries/1964-Douglas-MacArthur.txt',
 '../docs/NYT-Obituaries/1965-Churchill.txt',
 '../docs/NYT-Obituaries/1962-William-Faulkner.txt',
 '../docs/NYT-Obituaries/1956-Babe-Zaharias.txt',
 '../docs/NYT-Obituaries/1932-John-Philip-Sousa.txt',
 '../docs/NYT-Obituaries/1964-Herbert-Hoover.txt',
 '../docs/NYT-Obituaries/1961-Sam-Rayburn.txt',
 '../docs/NYT-Obituaries/1954-Lionel-Barrymore.txt',
 '../docs/NYT-Obituaries/1998-Frank-Sinatra.txt',
 '../docs/NYT-Obituaries/1948-Babe-Ruth.txt',
 '../docs/NYT-Obituaries/1947-Willa-Cather.txt',
 '../docs/NYT-Obituaries/1963-John-F-Kennedy.txt',
 '../docs/NYT-Obituaries/1975-Walker-Evans.txt',
 '../docs/NYT-Obituaries/1916-J-J-Hill.txt',
 '../docs/NYT-Obituaries/1980-Jesse-Owens.txt',
 '../docs/NYT-Obituaries/1948-Sergei-Eisenstein.txt',
 '../docs/NYT-Obituaries/1981-Robert-Moses.txt',
 '../docs/NYT-Obituaries/1989-Robert-Penn-Warren.txt',
 '../docs/NYT-Obituaries/1901-William-McKinley.txt',
 '../docs/NYT-Obituaries/1970-Walter-Reuther.txt',
 '../docs/NYT-Obituaries/1930-Balfour.txt',
 '../docs/NYT-Obituaries/1984-Indira-Gandhi.txt',
 '../docs/NYT-Obituaries/1978-Golda-Meir.txt',
 '../docs/NYT-Obituaries/1983-Earl-Hines.txt',
 '../docs/NYT-Obituaries/1974-Katharine-Cornell.txt',
 '../docs/NYT-Obituaries/1982-Lee-Strasberg.txt',
 '../docs/NYT-Obituaries/1939-Pope-Pius-XI.txt',
 '../docs/NYT-Obituaries/1886-Mary-Ewing-Outerbridge.txt',
 '../docs/NYT-Obituaries/1993-Dizzy-Gillespie.txt',
 '../docs/NYT-Obituaries/1910-Florence-Nightingale.txt',
 '../docs/NYT-Obituaries/1960-Richard-Wright.txt',
 '../docs/NYT-Obituaries/1986-The-Challenger.txt',
 '../docs/NYT-Obituaries/1992-Menachem-Begin.txt',
 '../docs/NYT-Obituaries/1998-Galina-Ulanova.txt',
 '../docs/NYT-Obituaries/1976-Max-Ernst.txt',
 '../docs/NYT-Obituaries/1993-Cesar-Chavez.txt',
 '../docs/NYT-Obituaries/1965-Adlai-Ewing-Stevenson.txt',
 '../docs/NYT-Obituaries/1935-Adolph-S-Ochs.txt',
 '../docs/NYT-Obituaries/1941-Lou-Gehrig.txt',
 '../docs/NYT-Obituaries/1961-Carl-G-Jung.txt',
 '../docs/NYT-Obituaries/1963-Robert-Frost.txt',
 '../docs/NYT-Obituaries/1965-Edward-R-Murrow.txt',
 '../docs/NYT-Obituaries/1971-Dean-Acheson.txt',
 '../docs/NYT-Obituaries/1986-Jorge-Luis-Borges.txt',
 '../docs/NYT-Obituaries/1966-Walt-Disney.txt',
 '../docs/NYT-Obituaries/1996-Carl-Sagan.txt',
 '../docs/NYT-Obituaries/1959-Ross-G-Harrison.txt',
 '../docs/NYT-Obituaries/1945-Jerome-Kern.txt',
 '../docs/NYT-Obituaries/1991-Frank-Capra.txt',
 '../docs/NYT-Obituaries/1987-Andres-Segovie.txt',
 '../docs/NYT-Obituaries/1987-Rita-Hayworth.txt',
 '../docs/NYT-Obituaries/1993-William-Golding.txt',
 '../docs/NYT-Obituaries/1932-Florenz-Ziegfeld.txt',
 '../docs/NYT-Obituaries/1938-Constantin-Stanislavsky.txt']

In [3]:
# and collect obit titles, which are also the final section of the filepaths
obit_titles = [Path(file).stem for file in files]
obit_titles

['1945-Adolf-Hitler',
 '1915-F-W-Taylor',
 '1975-Chiang-Kai-shek',
 '1984-Ethel-Merman',
 '1953-Jim-Thorpe',
 '1964-Nella-Larsen',
 '1955-Margaret-Abbott',
 '1984-Lillian-Hellman',
 '1959-Cecil-De-Mille',
 '1928-Mabel-Craty',
 '1973-Eddie-Rickenbacker',
 '1989-Ferdinand-Marcos',
 '1991-Martha-Graham',
 '1997-Deng-Xiaoping',
 '1938-George-E-Hale',
 '1885-Ulysses-Grant',
 '1909-Sarah-Orne-Jewett',
 '1957-Christian-Dior',
 '1987-Clare-Boothe-Luce',
 '1976-Jacques-Monod',
 '1954-Getulio-Vargas',
 '1979-Stan-Kenton',
 '1990-Leonard-Bernstein',
 '1972-Jackie-Robinson',
 '1998-Fred-W-Friendly',
 '1991-Leo-Durocher',
 '1915-B-T-Washington',
 '1997-James-Stewart',
 '1981-Joe-Louis',
 '1983-Muddy-Waters',
 '1942-George-M-Cohan',
 '1989-Samuel-Beckett',
 '1962-Marilyn-Monroe',
 '2000-Charles-M-Schulz',
 '1967-Gregory-Pincus',
 '1894-R-L-Stevenson',
 '1978-Bruce-Catton',
 '1982-Arthur-Rubinstein',
 '1875-Andrew-Johnson',
 '1974-Charles-Lindbergh',
 '1964-Rachel-Carson',
 '1953-Marjorie-Rawlings',
 '1973-Otto-Klemperer',
 '1963-Sylvia-Plath',
 '1956-Charles-Merrill',
 '1966-Lenny-Bruce',
 '1908-Cleveland',
 '1982-Anna-Freud',
 '1941-Frank-Conrad',
 '1966-Alfred-P-Sloan-Jr',
 '1960-Beno-Gutenberg',
 '1976-J-Paul-Getty',
 '1891-P-T-Barnum',
 '1901-Queen-Victoria',
 '1970-Erich-Maria-Remarque',
 '1989-August-A-Busch-Jr',
 '1992-John-Cage',
 '1994-Erik-Erikson',
 '1990-Erte',
 '1966-Chester-Nimitz',
 '1954-Enrico-Fermi',
 '1961-Primitive-Artist',
 '1945-Bela-Bartok',
 '1978-Pope-Paul-VI',
 '1965-Martin-Buber',
 '1971-Diane-Arbus',
 '1973-Lyndon-Johnson',
 '1998-Bob-Kane',
 '1969-Judy-Garland',
 '1959-Frank-Lloyd-Wright',
 '1995-Ginger-Rogers',
 '1920-Marlene-Dietrich',
 '1998-Alan-B-Shepard-Jr',
 '1971-Khrushchev',
 '1935-Justice-Holmes',
 '1969-David-Eisenhower',
 '1992-Marsha-P-Johnson',
 '1914-Alfred-Thayer-Mahan',
 '1965-Branch-Rickey',
 '1965-Albert-Schweitzer',
 '1992-Isaac-Asimov',
 '1989-William-B-Shockley',
 '1910-William-James',
 '1951-Fanny-Brice',
 '1916-Jack-London',
 '1947-Al-Capone',
 '1989-Lucille-Ball',
 '1980-Jean-Paul-Sartre',
 '1969-Sonja-Henie',
 '1976-Adolph-Zukor',
 '1959-John-Dulles',
 '1980-Alfred-Hitchcock',
 '1901-Benjamin-Harrison',
 '1994-Richard-Nixon',
 '1917-Hilaire-G-E-Degas',
 '1987-James-Baldwin',
 '1941-Virginia-Woolf',
 '1922-Alexander-Graham-Bell',
 '1907-Qiu-Jin',
 '1895-Fred-Douglass',
 '1971-Florence-Blanchfield',
 '1984-Ray-A-Kroc',
 '1947-Fiorello-La-Guardia',
 '1988-Louis-L-Amour',
 '1902-Elizabeth-Cady-Stanton',
 '1965-Shirley-Jackson',
 '1979-John-Wayne',
 '1994-Thomas-P-O-Neill-Jr',
 '1982-Thelonious-Monk',
 '1919-C-J-Walker',
 '1954-Liberty-H-Bailey',
 '1977-Dash-Ended',
 '1936-Maxim-Gorky',
 '2000-Pierre-Trudeau',
 '1976-Mao-Tse-Tung',
 '1955-Walter-White',
 '1930-Conan-Doyle',
 '1995-Jonas-Salk',
 '1949-Mitchell',
 '1951-Henrietta-Lacks',
 '1903-James-M-N-Whistler',
 '1950-A-J-Dempster',
 '1937-Edith-Wharton',
 '1935-Jane-Addams',
 '1941-James-Joyce',
 '1952-John-Dewey',
 '1940-Marcus-Garvey',
 '1971-Louis-Armstrong',
 '1923-Warren-Harding',
 '1937-John-Rockefeller',
 '2000-Elliot-Richardson',
 '1972-J-Edgar-Hoover',
 '1975-Franco',
 '1973-Jeanette-Rankin',
 '1888-Louisa-M-Alcott',
 '1977-Charles-Chaplin',
 '1990-Ralph-David-Abernathy',
 '1946-Lord-Keynes',
 '1996-Gene-Kelly',
 '1973-Roberto-Clemente',
 '1986-Georgia-O-Keeffe',
 '1990-Rex-Harrison',
 '1916-Martian-Theory',
 '1961-Ernest-Hemingway',
 '1978-Margaret-Mead',
 '1982-Ingrid-Bergman',
 '1946-C-E-M-Clung',
 '1977-Maria-Callas',
 '1952-Eva-Peron',
 '1961-Emily-Balch',
 '1979-Arthur-Fiedler',
 '1896-Harriet-Beecher-Stowe',
 '1989-Andrei-Sakharov',
 '1939-W-B-Yeats',
 '1961-Hammarskjold',
 '1969-Madhubala',
 '1970-Edouard-Daladier',
 '1988-John-Houseman',
 '1992-William-Shawn',
 '1950-Edna-St-V-Millay',
 '1989-Claude-Pepper',
 '1929-Marie-Curie',
 '1972-The-Duke-of-Windsor',
 '1984-Count-Basie',
 '1998-Helen-Moody',
 '1936-Anne-Macy',
 '1900-Nietzsche',
 '1880-Lucretia-Mott',
 '1967-J-Robert-Oppenheimer',
 '1984-Richard-Burton',
 '1964-Sean-O-Casey',
 '1931-Thomas-Edison',
 '1971-Bobby-Jones',
 '1914-John-P-Holland',
 '1995-George-Abbott',
 '1950-Henry-L-Stimson',
 '1955-Dale-Carnegie',
 '1934-T-A-Watson',
 '1968-Martin-Luther-King-Jr',
 '1933-Louis-C-Tiffany',
 '1909-Geronimo',
 '1952-Charles-Spaulding',
 '1922-Nellie-Bly',
 '1955-Cy-Young',
 '1993-Arthur-Ashe',
 '1986-Bernard-Malamud',
 '1939-Howard-Carter',
 '1994-Linus-C-Pauling',
 '1967-Langston-Hughes',
 '1948-Mohandas-K-Gandhi',
 '1931-Melvil-Dewey',
 '1969-Everett-Dirksen',
 '1968-Helen-Keller',
 '1992-Alex-Haley',
 '1953-Eugene-O-Neill',
 '1981-Anwar-el-Sadat',
 '1937-Maurice-Ravel',
 '1966-Margaret-Sanger',
 '1989-I-F-Stone',
 '1943-J-H-Kellogg',
 '1985-Roger-Maris',
 '1972-Mahalia-Jackson',
 '1990-Greta-Garbo',
 '1998-Benjamin-Spock',
 '1994-Jessica-Tandy',
 '1979-Richard-Rodgers',
 '1958-W-C-Handy',
 '1974-Ed-Sullivan',
 '1989-Hirohito',
 '1933-Calvin-Coolidge',
 '1969-Ho-Chi-Minh',
 '1987-John-Huston',
 '1984-Johnny-Weissmuller',
 '1969-Maureen-Connolly',
 '1968-Yuri-Gagarin',
 '1991-Peggy-Ashcroft',
 '1979-A-Philip-Randolph',
 '1946-Gertrude-Stein',
 '1993-Thurgood-Marshall',
 '1887-Emma-Lazarus',
 '1986-James-Cagney',
 '1976-Richard-Daley',
 '1977-Joan-Crawford',
 '1971-Hugo-Black',
 '1954-Henri-Matisse',
 '1906-Susan-B-Anthony',
 '1990-Sammy-Davis-Jr',
 '1914-John-Muir',
 '1954-Anne-O-Hare-McCormick',
 '1986-Kate-Smith',
 '1919-Anna-H-Shaw',
 '1980-Jean-Piaget',
 '1966-Buster-Keaton',
 '1997-Allen-Ginsberg',
 '1991-Miles-Davis',
 '1982-Satchel-Paige',
 '1931-Ida-B-Wells',
 '1967-Henry-R-Luce',
 '1984-Ansel-Adams',
 '1945-Ernie-Pyle',
 '1952-Chaim-Weizmann',
 '1973-Nancy-Mitford',
 '1852-Ada-Lovelace',
 '1996-Timothy-Leary',
 '1919-Carnegie-Started',
 '1989-Andrei-A-Gromyko',
 '1965-David-O-Selznick',
 '1870-Robert-E-Lee',
 '1968-Robert-Francis-Kennedy',
 '1900-Stephen-Crane',
 '1936-John-W-Heisman',
 '1998-Maureen-O-Sullivan',
 '1953-Joseph-Stalin',
 '1944-Alfred-E-Smith',
 '1910-Tolstoy',
 '1964-Cole-Porter',
 '1983-Jack-Dempsey',
 '1975-Haile-Selassie',
 '1882-Charles-Darwin',
 '1903-Emily-Warren-Roebling',
 '1962-Eleanor-Roosevelt',
 '1926-Harry-Houdini',
 '1955-Albert-Einstein',
 '1971-Coco-Chanel',
 '1959-Billie-Holiday',
 '1969-Coleman-Hawkins',
 '1954-Frida-Kahlo',
 '1911-Joseph-Pulitzer',
 '1993-Carlos-Montoya',
 '1947-Max-Planck',
 '1985-Orson-Welles',
 '1974-Earl-Warren',
 '1971-Ralph-Bunche',
 '1999-Hassan-II',
 '1931-Knute-Rocke',
 '1998-Theodore-Schultz',
 '1960-Boris-Pasternak',
 '1927-Victoria-Martin',
 '1943-George-Washington-Carver',
 '1956-Thomas-J-Watson-Sr',
 '1947-Henry-Ford',
 '1953-Fred-Vinson',
 '1982-Leonid-Brezhnev',
 '1999-King-Hussein',
 '1930-Elmer-Sperry',
 '1985-E-B-White',
 '1959-Ethel-Barrymore',
 '1986-Benny-Goodman',
 '1963-W-E-B-DuBois',
 '1975-Elijah-Muhammad',
 '1973-Pablo-Picasso',
 '1993-Federico-Fellini',
 '1945-Harry-S-Truman',
 '1970-De-Gaulle-Rallied',
 '1995-Alfred-Eisenstaedt',
 '1999-Iris-Murdoch',
 '1987-Alf-Landon',
 '1998-Bella-Abzug',
 '1940-Scott-Fitzgerald',
 '1989-Vladimir-Horowitz',
 '1969-Mies-van-der-Rohe',
 '1944-Ida-M-Tarbell',
 '1948-John-Pershing',
 '1938-Clarence-Darrow',
 '1987-Primo-Levi',
 '1971-Igor-Stravinsky',
 '1945-George-Patton',
 '1930-William-Howard-Taft',
 '1935-Will-Rogers',
 '1992-Shirley-Booth',
 '1994-Jacqueline-Kennedy',
 '1933-Ring-Lardner',
 '1974-Sylvia-Plath',
 '1945-FDR',
 '1995-Yitzhak-Rabin',
 '1960-Emily-Post',
 '1984-Truman-Capote',
 '1968-Upton-Sinclair',
 '1994-Jan-Tinbergen',
 '1957-Gerard-Swope',
 '1993-Albert-Sabin',
 '1955-Thomas-Mann',
 '1991-Dr-Seuss',
 '1877-Bedford-Forrest',
 '1964-Douglas-MacArthur',
 '1965-Churchill',
 '1962-William-Faulkner',
 '1956-Babe-Zaharias',
 '1932-John-Philip-Sousa',
 '1964-Herbert-Hoover',
 '1961-Sam-Rayburn',
 '1954-Lionel-Barrymore',
 '1998-Frank-Sinatra',
 '1948-Babe-Ruth',
 '1947-Willa-Cather',
 '1963-John-F-Kennedy',
 '1975-Walker-Evans',
 '1916-J-J-Hill',
 '1980-Jesse-Owens',
 '1948-Sergei-Eisenstein',
 '1981-Robert-Moses',
 '1989-Robert-Penn-Warren',
 '1901-William-McKinley',
 '1970-Walter-Reuther',
 '1930-Balfour',
 '1984-Indira-Gandhi',
 '1978-Golda-Meir',
 '1983-Earl-Hines',
 '1974-Katharine-Cornell',
 '1982-Lee-Strasberg',
 '1939-Pope-Pius-XI',
 '1886-Mary-Ewing-Outerbridge',
 '1993-Dizzy-Gillespie',
 '1910-Florence-Nightingale',
 '1960-Richard-Wright',
 '1986-The-Challenger',
 '1992-Menachem-Begin',
 '1998-Galina-Ulanova',
 '1976-Max-Ernst',
 '1993-Cesar-Chavez',
 '1965-Adlai-Ewing-Stevenson',
 '1935-Adolph-S-Ochs',
 '1941-Lou-Gehrig',
 '1961-Carl-G-Jung',
 '1963-Robert-Frost',
 '1965-Edward-R-Murrow',
 '1971-Dean-Acheson',
 '1986-Jorge-Luis-Borges',
 '1966-Walt-Disney',
 '1996-Carl-Sagan',
 '1959-Ross-G-Harrison',
 '1945-Jerome-Kern',
 '1991-Frank-Capra',
 '1987-Andres-Segovie',
 '1987-Rita-Hayworth',
 '1993-William-Golding',
 '1932-Florenz-Ziegfeld',
 '1938-Constantin-Stanislavsky']

## Create document-term matrix

### Initiate CountVectorizer as vectorizer

Remember document-term matrices, aka doc-term matrices, aka dtms? We learned about them in notebooks 10 and 11. We build it with scikit-learn's CountVectorizer, which we imported at the start of the lesson. 

When we load our vectorizer, we include an argument to encode as utf-8 and we load our stopwords. We can also set the minimum number of times a word must appear in the corpus to be included in the dtm. In this case, I've set it at 20.

In [4]:
# load stopwords
from sklearn.feature_extraction import text
text.ENGLISH_STOP_WORDS

frozenset({'a',
           'about',
           'above',
           'across',
           'after',
           'afterwards',
           'again',
           'against',
           'all',
           'almost',
           'alone',
           'along',
           'already',
           'also',
           'although',
           'always',
           'am',
           'among',
           'amongst',
           'amoungst',
           'amount',
           'an',
           'and',
           'another',
           'any',
           'anyhow',
           'anyone',
           'anything',
           'anyway',
           'anywhere',
           'are',
           'around',
           'as',
           'at',
           'back',
           'be',
           'became',
           'because',
           'become',
           'becomes',
           'becoming',
           'been',
           'before',
           'beforehand',
           'behind',
           'being',
           'below',
           'beside',
           'besides',
           'between',
           'beyond',
           'bill',
           'both',
           'bottom',
           'but',
           'by',
           'call',
           'can',
           'cannot',
           'cant',
           'co',
           'con',
           'could',
           'couldnt',
           'cry',
           'de',
           'describe',
           'detail',
           'do',
           'done',
           'down',
           'due',
           'during',
           'each',
           'eg',
           'eight',
           'either',
           'eleven',
           'else',
           'elsewhere',
           'empty',
           'enough',
           'etc',
           'even',
           'ever',
           'every',
           'everyone',
           'everything',
           'everywhere',
           'except',
           'few',
           'fifteen',
           'fifty',
           'fill',
           'find',
           'fire',
           'first',
           'five',
           'for',
           'former',
           'formerly',
           'forty',
           'found',
           'four',
           'from',
           'front',
           'full',
           'further',
           'get',
           'give',
           'go',
           'had',
           'has',
           'hasnt',
           'have',
           'he',
           'hence',
           'her',
           'here',
           'hereafter',
           'hereby',
           'herein',
           'hereupon',
           'hers',
           'herself',
           'him',
           'himself',
           'his',
           'how',
           'however',
           'hundred',
           'i',
           'ie',
           'if',
           'in',
           'inc',
           'indeed',
           'interest',
           'into',
           'is',
           'it',
           'its',
           'itself',
           'keep',
           'last',
           'latter',
           'latterly',
           'least',
           'less',
           'ltd',
           'made',
           'many',
           'may',
           'me',
           'meanwhile',
           'might',
           'mill',
           'mine',
           'more',
           'moreover',
           'most',
           'mostly',
           'move',
           'much',
           'must',
           'my',
           'myself',
           'name',
           'namely',
           'neither',
           'never',
           'nevertheless',
           'next',
           'nine',
           'no',
           'nobody',
           'none',
           'noone',
           'nor',
           'not',
           'nothing',
           'now',
           'nowhere',
           'of',
           'off',
           'often',
           'on',
           'once',
           'one',
           'only',
           'onto',
           'or',
           'other',
           'others',
           'otherwise',
           'our',
           'ours',
           'ourselves',
           'out',
           'over',
           'own',
           'part',
           'per',
           'perhaps',
           'please',
           'put',
           'rather',
           're',
           'same',
           'see',
           'seem',
           'seemed',
           'seeming',
           'seems',
           'serious',
           'several',
           'she',
           'should',
           'show',
           'side',
           'since',
           'sincere',
           'six',
           'sixty',
           'so',
           'some',
           'somehow',
           'someone',
           'something',
           'sometime',
           'sometimes',
           'somewhere',
           'still',
           'such',
           'system',
           'take',
           'ten',
           'than',
           'that',
           'the',
           'their',
           'them',
           'themselves',
           'then',
           'thence',
           'there',
           'thereafter',
           'thereby',
           'therefore',
           'therein',
           'thereupon',
           'these',
           'they',
           'thick',
           'thin',
           'third',
           'this',
           'those',
           'though',
           'three',
           'through',
           'throughout',
           'thru',
           'thus',
           'to',
           'together',
           'too',
           'top',
           'toward',
           'towards',
           'twelve',
           'twenty',
           'two',
           'un',
           'under',
           'until',
           'up',
           'upon',
           'us',
           'very',
           'via',
           'was',
           'we',
           'well',
           'were',
           'what',
           'whatever',
           'when',
           'whence',
           'whenever',
           'where',
           'whereafter',
           'whereas',
           'whereby',
           'wherein',
           'whereupon',
           'wherever',
           'whether',
           'which',
           'while',
           'whither',
           'who',
           'whoever',
           'whole',
           'whom',
           'whose',
           'why',
           'will',
           'with',
           'within',
           'without',
           'would',
           'yet',
           'you',
           'your',
           'yours',
           'yourself',
           'yourselves'})

In [5]:
text_file = open('../docs/jockers_stopwords.txt')
jockers_words = text_file.read().split()
jockers_words

['0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 'a',
 'aaron',
 'abbey',
 'abbie',
 'abdul',
 'abe',
 'across',
 'abel',
 'abigail',
 'about',
 'above',
 'abraham',
 'abram',
 'abst',
 'accordance',
 'according',
 'act',
 'actually',
 'ada',
 'adah',
 'adalberto',
 'adaline',
 'adam',
 'adan',
 'added',
 'among',
 'addie',
 'adela',
 'adelaida',
 'adelaide',
 'adele',
 'adelia',
 'adelina',
 'adeline',
 'adell',
 'adella',
 'adelle',
 'adena',
 'adina',
 'adj',
 'adolfo',
 'adolph',
 'adopted',
 'adria',
 'adrian',
 'adriana',
 'adriane',
 'adrianna',
 'adrien',
 'adrienne',
 'after',
 'afterwards',
 'afton',
 'again',
 'against',
 'agatha',
 'agnes',
 'agnus',
 'agueda',
 'agustina',
 'ahmad',
 'ahmed',
 'ai',
 'aida',
 'besides',
 'aide',
 'aiko',
 'aileen',
 'ailene',
 'aimee',
 'aja',
 'akilah',
 'al',
 'alaina',
 'alaine',
 'alan',
 'alana',
 'alane',
 'alanna',
 'alayna',
 'alba',
 'albert',
 'alberta',
 'albertha',
 'albertina',
 'albertine',
 'alberto',
 'albina',
 'alda',
 'alden',
 'aldo',
 'alease',
 'alec',
 'alecia',
 'e',
 'aleen',
 'aleisha',
 'eg',
 'alejandra',
 'alejandrina',
 'alejandro',
 'alena',
 'elsewhere',
 'alene',
 'alesha',
 'aleshia',
 'alesia',
 'alessandra',
 'aleta',
 'aletha',
 'everywhere',
 'alethea',
 'alethia',
 'alex',
 'alexander',
 'alexandria',
 'alexia',
 'alexis',
 'alfonso',
 'alfonzo',
 'alfred',
 'alfreda',
 'alfredia',
 'alfredo',
 'ali',
 'alia',
 'alica',
 'alice',
 'alicia',
 'alida',
 'alina',
 'alisa',
 'alise',
 'had',
 'alisha',
 'alishia',
 'alisia',
 'alison',
 'alissa',
 'alita',
 'alix',
 'aliza',
 'all',
 'alla',
 'allan',
 'alleen',
 'allegra',
 'allen',
 'allena',
 'allene',
 'allie',
 'alline',
 'allison',
 'allyn',
 'allyson',
 'alma',
 'hop',
 'almeda',
 'almeta',
 'almost',
 'alona',
 'alone',
 'along',
 'alonso',
 'alonzo',
 'alpha',
 'alphonse',
 'alphonso',
 'already',
 'also',
 'alta',
 'altagracia',
 'altha',
 'althea',
 'although',
 'alton',
 'alva',
 'alvaro',
 'alvera',
 'alverta',
 'alvin',
 'alvina',
 'always',
 'alyce',
 'alycia',
 'alysa',
 'alyse',
 'alysha',
 'alysia',
 'alyson',
 'alyssa',
 'am',
 'amado',
 'amal',
 'amalia',
 'amanda',
 'amber',
 'amberly',
 'ambrose',
 'amee',
 'amelia',
 'long',
 'america',
 'm',
 'ami',
 'amie',
 'amiee',
 'amina',
 'may',
 'amira',
 'ammie',
 'amongst',
 'amos',
 'might',
 'amparo',
 'amy',
 'an',
 'ana',
 'anabel',
 'anamaria',
 'anastacia',
 'anastasia',
 'and',
 'andera',
 'anderson',
 'andra',
 'andre',
 'na',
 'andrea',
 'andreas',
 'andres',
 'andrew',
 'andria',
 'andy',
 'anette',
 'angel',
 'angela',
 'angele',
 'angelena',
 'angeles',
 'angelia',
 'angelic',
 'angelica',
 'angelina',
 'angeline',
 'angelique',
 'angelita',
 'angella',
 'angelo',
 'angelyn',
 'angie',
 'angila',
 'angla',
 'angle',
 'anglea',
 'anh',
 'anibal',
 'anika',
 'anisha',
 'anissa',
 'anita',
 'anitra',
 'anjanette',
 'anjelica',
 'ann',
 'anna',
 'annabel',
 'annabell',
 'annabelle',
 'overall',
 'annalee',
 'annalisa',
 'annamae',
 'annamaria',
 'annamarie',
 'anne',
 'anneliese',
 'annelle',
 'annemarie',
 'put',
 'annetta',
 'annice',
 'annie',
 'rather',
 'annika',
 'annis',
 'annmarie',
 'announce',
 'another',
 'answered',
 'anthony',
 'antione',
 'antionette',
 'antoine',
 'anton',
 'antone',
 'antonetta',
 'antonette',
 'antonia',
 'antonietta',
 'antonina',
 'antonio',
 'antony',
 'antwan',
 'any',
 'anya',
 'anyhow',
 'anyone',
 'anything',
 'anywhere',
 'apolonia',
 'april',
 'apryl',
 'ara',
 'should',
 'araceli',
 'aracelis',
 'aracely',
 'arcelia',
 'archie',
 'ardath',
 'ardelia',
 'ardell',
 'ardella',
 'ardelle',
 'arden',
 'ardis',
 'ardith',
 'are',
 'aren',
 'arent',
 'aretha',
 'argelia',
 'argentina',
 'ariana',
 'arianna',
 'arianne',
 'arica',
 'arie',
 'ariel',
 'arielle',
 'arla',
 'arlean',
 'arleen',
 'arlen',
 'there',
 'arlena',
 'arlene',
 'arletha',
 'arletta',
 'arlette',
 'arlie',
 'arlinda',
 'arline',
 'arlyne',
 'armand',
 'armanda',
 'they',
 'armandina',
 'armando',
 'armida',
 'arminda',
 'arnetta',
 'arnette',
 'arnita',
 'arnold',
 'arnoldo',
 'arnulfo',
 'around',
 'arron',
 'three',
 'art',
 'arthur',
 'artie',
 'arturo',
 'arvilla',
 'as',
 'asa',
 'asha',
 'ashanti',
 'ashely',
 'ashlea',
 'toward',
 'ashlee',
 'ashleigh',
 'ashley',
 'ashli',
 'ashlie',
 'ashly',
 'ashlyn',
 'asia',
 'ask',
 'unlikely',
 'asked',
 'asley',
 'assunta',
 'astrid',
 'ups',
 'at',
 'athena',
 'aubrey',
 'audie',
 'audra',
 'audrea',
 'audrey',
 'audria',
 'audrie',
 'audry',
 'august',
 'augusta',
 'augustina',
 'augustine',
 'augustus',
 'aundrea',
 'aura',
 'aurea',
 'aurelia',
 'aurelio',
 'aurora',
 'aurore',
 'austin',
 'auth',
 'autumn',
 'ava',
 'available',
 'avelina',
 'avery',
 'avis',
 'avril',
 'awilda',
 'ayako',
 'ayana',
 'ayanna',
 'ayesha',
 'azalee',
 'azucena',
 'azzie',
 'b',
 'babara',
 'babette',
 'back',
 'bailey',
 'bambi',
 'bao',
 'barabara',
 'barb',
 'barbara',
 'barbera',
 'barbie',
 'barbra',
 'bari',
 'barney',
 'barrett',
 'barrie',
 'bart',
 'basil',
 'would',
 'basilia',
 'be',
 'bea',
 'beata',
 'beatrice',
 'beatris',
 'beatriz',
 'beau',
 'beaulah',
 'bebe',
 'became',
 'because',
 'becki',
 'becky',
 'become',
 'becomes',
 'becoming',
 'bee',
 'abby',
 'been',
 'before',
 'beforehand',
 'begin',
 'beginning',
 'behind',
 'being',
 'belen',
 'belia',
 'belinda',
 'belkis',
 'bell',
 'bella',
 'belle',
 'below',
 'ben',
 'benedict',
 'benita',
 'benito',
 'benjamin',
 'bennett',
 'benny',
 'benton',
 'berenice',
 'berna',
 'bernadette',
 'bernadine',
 'bernard',
 'bernarda',
 'bernardina',
 'bernardine',
 'bernardo',
 'adrianne',
 'berneice',
 'adriene',
 'bernice',
 'bernie',
 'berniece',
 'bernita',
 'bert',
 'agripina',
 'berta',
 'agustin',
 'bertha',
 'bertie',
 'bertram',
 'beryl',
 'beside',
 'bess',
 'bessie',
 'best',
 'beth',
 'bethanie',
 'aisha',
 'bethann',
 'akiko',
 'bethany',
 'bethel',
 'betsey',
 'bette',
 'better',
 'bettie',
 'bettina',
 'betty',
 'bettyann',
 'bettye',
 'between',
 'beula',
 'beulah',
 'bev',
 'beverlee',
 'beverley',
 'beverly',
 'beyond',
 'bianca',
 'bibi',
 'bill',
 'billie',
 'billy',
 'billye',
 'aleida',
 'birdie',
 'birgit',
 'blaine',
 'blair',
 'blake',
 'blanca',
 'blanch',
 'blanche',
 'blondell',
 'blossom',
 'blythe',
 'bo',
 'bobbi',
 'bobbie',
 'bobbye',
 'alexa',
 'bok',
 'alexandra',
 'bong',
 'bonita',
 'bonnie',
 'bonny',
 'booker',
 'boris',
 'both',
 'boyce',
 'boyd',
 'brad',
 'bradford',
 'bradley',
 'bradly',
 'brady',
 'brain',
 'branda',
 'aline',
 'brande',
 'brandee',
 'branden',
 'brandi',
 'brandon',
 'brandy',
 'brant',
 'breana',
 'breann',
 'breanna',
 'breanne',
 'bree',
 'brenda',
 'brendan',
 'brendon',
 'brenna',
 'brent',
 'brenton',
 'bret',
 'brett',
 'brian',
 'briana',
 'brianne',
 'brice',
 'bridget',
 'bridgett',
 'bridgette',
 'brigette',
 'brigid',
 'brigida',
 'brigitte',
 'brinda',
 'britany',
 'britney',
 'britni',
 'britt',
 'britta',
 'brittaney',
 'brittani',
 'brittanie',
 'britteny',
 'brittni',
 'brittny',
 'brock',
 'broderick',
 'bronwyn',
 'brook',
 'brooke',
 'brooks',
 'bruce',
 'amada',
 'bruna',
 'brunilda',
 'bruno',
 'bryan',
 'bryanna',
 'bryant',
 'bryce',
 'brynn',
 'bryon',
 'bud',
 'buddy',
 'buena',
 'buffy',
 'buford',
 'bula',
 'bunny',
 'burl',
 'burma',
 'burt',
 'burton',
 'buster',
 'but',
 'analisa',
 'by',
 'byron',
 'c',
 'ca',
 'caitlin',
 'caitlyn',
 'calandra',
 'caleb',
 'calista',
 'andree',
 'callie',
 'calvin',
 'camelia',
 'camellia',
 'cameron',
 'camie',
 'camila',
 'camilla',
 'camille',
 'cammy',
 'can',
 'candace',
 'candance',
 'angelika',
 'candelaria',
 'candi',
 'candice',
 'candida',
 'candis',
 'candy',
 'candyce',
 'cannot',
 'cant',
 'caprice',
 'caption',
 'cara',
 'caren',
 'carey',
 'cari',
 'anisa',
 'caridad',
 'carie',
 'carina',
 'carisa',
 'anja',
 'carissa',
 'carita',
 'carl',
 'carla',
 'carlee',
 'carleen',
 'carlena',
 'carlene',
 'carletta',
 'carley',
 'carli',
 'carline',
 'carlita',
 'carlo',
 'carlos',
 'carlota',
 'annett',
 'carlotta',
 'annette',
 'carlton',
 'carly',
 'carlyn',
 'carma',
 'annita',
 'carman',
 'carmel',
 'carmela',
 'carmelia',
 'carmelina',
 'antoinette',
 'carmelita',
 'carmella',
 'carmelo',
 'carmen',
 'carmina',
 'carmine',
 'carmon',
 'carol',
 'carola',
 'carolann',
 'carole',
 'carolee',
 'carolin',
 'caroline',
 'caroll',
 'carolyn',
 'carolyne',
 'carolynn',
 'caron',
 'caroyln',
 'carri',
 'carrie',
 'carrol',
 'carry',
 'carson',
 'cary',
 'caryl',
 'carylon',
 'caryn',
 'casandra',
 'casey',
 'casie',
 'ariane',
 'casimira',
 'cassandra',
 'cassaundra',
 'cassey',
 'cassidy',
 'cassie',
 'cassondra',
 'cassy',
 'catalina',
 'catarina',
 'caterina',
 'catharine',
 'catherin',
 'catherina',
 'catherine',
 'cathern',
 'catheryn',
 'cathey',
 'cathi',
 'cathie',
 'cathleen',
 'cathrine',
 'cathryn',
 'cathy',
 'catina',
 'catrice',
 'catrina',
 'cayla',
 'cecil',
 'cecila',
 'cecile',
 'aron',
 'cecilia',
 'cecille',
 'cecily',
 'cedric',
 'cedrick',
 'celena',
 'celesta',
 'celeste',
 'celestina',
 'celestine',
 'celia',
 'celina',
 'celinda',
 'celine',
 'celsa',
 'ceola',
 'cesar',
 'chad',
 'ashton',
 'chadwick',
 'chae',
 'chan',
 'chana',
 'asuncion',
 'chance',
 'chanda',
 'chandra',
 'chanel',
 'chanell',
 'chanelle',
 'chang',
 'chantal',
 'chantay',
 'chante',
 'chantel',
 'chantell',
 'chantelle',
 'chapter',
 'chara',
 'charis',
 'charise',
 'charissa',
 'charisse',
 'charita',
 'charity',
 'charla',
 'charlena',
 'charlene',
 'charles',
 'charlesetta',
 'charlette',
 'charley',
 'charlie',
 'charline',
 'charlott',
 'charlotte',
 'charlsie',
 'charlyn',
 'charmaine',
 'charolette',
 'chase',
 'chasidy',
 'chasity',
 'chastity',
 'chau',
 'chauncey',
 'chaya',
 'barbar',
 'chelsea',
 'chelsey',
 'chelsie',
 'cher',
 'chere',
 'cheree',
 'cherelle',
 'cheri',
 'barry',
 'cherie',
 'barton',
 'cherilyn',
 'cherish',
 'cherlyn',
 'cherri',
 'cherrie',
 'cherry',
 'cherryl',
 'chery',
 'cheryl',
 'cheryle',
 'cheryll',
 'beckie',
 'chester',
 'chet',
 'cheyenne',
 'chi',
 'chia',
 'chieko',
 'chin',
 'china',
 'ching',
 'belva',
 'chiquita',
 'chloe',
 'chong',
 'chris',
 'chrissy',
 'christa',
 'bennie',
 'christal',
 'christeen',
 'christel',
 'christen',
 'christene',
 'christi',
 'christia',
 'christian',
 'christiana',
 'christiane',
 'christie',
 'christin',
 'bernetta',
 'christina',
 'christine',
 'christinia',
 'christoper',
 'berry',
 'christopher',
 'christy',
 'chrystal',
 'chu',
 'chuck',
 'chun',
 'chung',
 'cicely',
 'ciera',
 'cierra',
 'cinda',
 'cinderella',
 'cindi',
 'cindy',
 'betsy',
 'cinthia',
 'cira',
 'clair',
 'clara',
 'clare',
 'clarence',
 'claretha',
 'claretta',
 'claribel',
 'clarice',
 'clarine',
 'claris',
 'clarisa',
 'clarissa',
 'clarita',
 'billi',
 'clark',
 'classie',
 'claud',
 'claude',
 'claudette',
 'claudia',
 'claudie',
 'claudine',
 'claudio',
 'clay',
 'clayton',
 'clemencia',
 'clement',
 'clemente',
 'clementina',
 'bob',
 'clementine',
 'clemmie',
 'bobby',
 'cleo',
 'bobette',
 'cleopatra',
 'cleora',
 'cleotilde',
 'cleta',
 'cletus',
 'cleveland',
 ...]

In [6]:
new_stopwords = text.ENGLISH_STOP_WORDS.union(jockers_words)
new_stopwords

frozenset({'basil',
           'tempie',
           'madalene',
           'cecille',
           'ranae',
           'griselda',
           'jadwiga',
           'brandee',
           'clement',
           'melba',
           'pp',
           'charmain',
           'toward',
           'katherina',
           'marcella',
           'yon',
           'enough',
           'phil',
           'valarie',
           'sherita',
           'heather',
           'annice',
           'adaline',
           'darlene',
           'stephane',
           'russell',
           'recently',
           'christena',
           'irwin',
           'melodi',
           'ana',
           'andra',
           'kareen',
           'esteban',
           'go',
           'kathrin',
           'vincenzo',
           'thersa',
           'dulce',
           'margrett',
           'brant',
           'mardell',
           'laurence',
           'ozell',
           'shaquita',
           'luisa',
           'thereby',
           'cortney',
           'sheron',
           'violette',
           'corliss',
           'sherryl',
           'joane',
           'whom',
           'daryl',
           'tawnya',
           'carmina',
           'jarod',
           'keren',
           'tamatha',
           'cyrstal',
           'katrice',
           'celine',
           'stacie',
           'kristan',
           'su',
           'cortez',
           'theo',
           'jonell',
           'bertha',
           'delmy',
           'magda',
           'tyson',
           'frances',
           'reyes',
           'melita',
           'adriene',
           'stacia',
           'stefanie',
           'kimbra',
           'merilyn',
           'matilde',
           'audrey',
           'craig',
           'ellan',
           'me',
           'juanita',
           'zelda',
           'hubert',
           'beatris',
           'clifton',
           'yuri',
           'z',
           'celina',
           'whatve',
           'nancie',
           'janette',
           'lashanda',
           'yang',
           'our',
           'lawrence',
           'machelle',
           'fatimah',
           'reggie',
           'monica',
           'johnetta',
           'tami',
           'mimi',
           'forty',
           'jerrod',
           'xiao',
           'rivka',
           'sheila',
           'catalina',
           'stan',
           'latashia',
           'andree',
           'janyce',
           'u',
           'chiquita',
           'lanny',
           'marquerite',
           'taylor',
           'mirtha',
           'way',
           'thousand',
           'hong',
           'roseline',
           'alberto',
           'glady',
           'shaunda',
           'asha',
           'nobody',
           'benny',
           'january',
           'randal',
           'kenisha',
           'clay',
           'elfreda',
           'mendy',
           'rosetta',
           'dinah',
           'micheal',
           'ronnie',
           'minh',
           'naomi',
           'denna',
           'winifred',
           'yolanda',
           'curtis',
           'nicolle',
           'octavio',
           'josefina',
           'saundra',
           'asley',
           'bibi',
           'antony',
           'rosette',
           'ashlyn',
           'anyhow',
           'which',
           'bunny',
           'lashawnda',
           'justina',
           'lacie',
           'norberto',
           'elene',
           'codi',
           'sid',
           'lizette',
           'rey',
           'skye',
           'theda',
           'doretta',
           'adela',
           'rebbecca',
           'matha',
           'santana',
           'anastacia',
           'ahmad',
           'spencer',
           'jeffrey',
           'cira',
           'jefferey',
           'tegan',
           'gena',
           'janean',
           'kia',
           'holli',
           'justa',
           'jestine',
           'lore',
           'becoming',
           'lavenia',
           'nora',
           'yajaira',
           'willene',
           'sterling',
           'anisa',
           'huey',
           'derick',
           'jayson',
           'vincent',
           'hester',
           'antoinette',
           'among',
           'sadie',
           'corrinne',
           'faviola',
           'jonna',
           'lanita',
           'summer',
           'debrah',
           'synthia',
           'zina',
           'blossom',
           'dovie',
           'carolin',
           'modesta',
           'nancey',
           'antonia',
           'na',
           'cammie',
           'nelia',
           'johnna',
           'clifford',
           'danilo',
           'kasie',
           'available',
           'leland',
           'margarette',
           'cristopher',
           'sebastian',
           'luana',
           'brice',
           'jc',
           'maudie',
           'eustolia',
           'katia',
           'meg',
           'susan',
           'lyndia',
           'waneta',
           'emerita',
           'chelsea',
           'mandy',
           'arletha',
           'tosha',
           'adina',
           'sanjuanita',
           'lonna',
           'alison',
           'solomon',
           'alethia',
           'felice',
           'irvin',
           'malvina',
           'lilian',
           'margarett',
           'noble',
           'cheryll',
           'gertrude',
           'raymon',
           'micki',
           'rebbeca',
           'both',
           'pura',
           'jamel',
           'victoria',
           'allen',
           'maricela',
           'loris',
           'less',
           'madelene',
           'erika',
           'lennie',
           'marge',
           'bradford',
           'caron',
           'jin',
           'javier',
           'christian',
           'constance',
           'made',
           'cristina',
           'ladawn',
           'merlyn',
           'myrle',
           'sharee',
           'junior',
           'jacqualine',
           'carlton',
           'about',
           'pamala',
           'ami',
           'kittie',
           'corazon',
           'edra',
           'devorah',
           'ora',
           'rolanda',
           'meggan',
           'ever',
           'cristi',
           'moon',
           'tobias',
           'sharita',
           'zachery',
           'tabetha',
           'romana',
           'ferne',
           'mari',
           'byron',
           'breann',
           'diane',
           'kelsey',
           'crysta',
           'drucilla',
           'christa',
           'patria',
           'carin',
           'venice',
           'liliana',
           'kathe',
           'eloise',
           'shanae',
           'within',
           'dale',
           'johna',
           'alverta',
           'isidro',
           'krishna',
           'shannon',
           'katharine',
           'ozie',
           'patrica',
           'nikia',
           'justine',
           'rodrigo',
           'lena',
           'cythia',
           'kerstin',
           'jessenia',
           'carola',
           'ona',
           'pedro',
           'elvira',
           'hung',
           'shery',
           'lino',
           'cecilia',
           'janna',
           'carlie',
           'lavada',
           'eliana',
           'horace',
           'buddy',
           'kandace',
           'yukiko',
           'erik',
           'timothy',
           'carla',
           'lien',
           'sueann',
           'gregory',
           'milton',
           '4',
           'cindy',
           'ingeborg',
           'sacha',
           'velia',
           'rickey',
           'yasuko',
           'now',
           'shawnee',
           'lesia',
           'waylon',
           'jenee',
           'ellsworth',
           'wilbur',
           'gwen',
           'ouida',
           'lilia',
           'sirena',
           'cleo',
           'latesha',
           'nilsa',
           'tari',
           'avis',
           'dwayne',
           'tamika',
           'hers',
           'dick',
           'gertrud',
           'deborah',
           'ramon',
           'elisha',
           'alvin',
           'lona',
           'he',
           'sidney',
           'laurene',
           'roxanna',
           'lorie',
           'linnea',
           'nakisha',
           'britteny',
           'adelina',
           'ericka',
           'sherill',
           'ines',
           'birgit',
           'rosalba',
           'mitchell',
           'dorthea',
           'edgar',
           'marivel',
           'coretta',
           'christiane',
           'renna',
           'sonya',
           'one',
           'devon',
           'elbert',
           'tammera',
           'elise',
           'bebe',
           'olympia',
           'wilhemina',
           'jeanett',
           '9',
           'mittie',
           'hipolito',
           'lashawna',
           'kenna',
           'zula',
           'edmond',
           'rupert',
           'domonique',
           'include',
           'marisela',
           'shaunna',
           'myrta',
           'angelina',
           'samatha',
           'brenton',
           'gearldine',
           'merissa',
           'elmer',
           'yuk',
           'ivan',
           'irving',
           'roxana',
           'fae',
           'rudolf',
           'michaela',
           'benita',
           'lakenya',
           'hortensia',
           'evonne',
           'samual',
           'daina',
           'lucie',
           'gricelda',
           'meantime',
           'sheri',
           'aleisha',
           'ramona',
           'devin',
           'rolande',
           'margarita',
           'lauri',
           'mohammad',
           'anne',
           'vella',
           'jerlene',
           'lue',
           'carlena',
           'micaela',
           'milo',
           'isabelle',
           'tanya',
           'jamie',
           'chantal',
           'brittanie',
           'mirta',
           'jenell',
           'anjanette',
           'kizzy',
           'maya',
           'mathilde',
           'reda',
           'claire',
           'eun',
           'genesis',
           'beverly',
           'lory',
           'crista',
           'roseann',
           'rosaline',
           'petrina',
           'winford',
           'leonel',
           'own',
           'jacquie',
           'dessie',
           'agnes',
           'hildred',
           'rex',
           'seema',
           'major',
           'jeannine',
           'gracie',
           'dante',
           'amelia',
           'moshe',
           'lael',
           'beth',
           'damaris',
           'lecia',
           'danielle',
           'rudy',
           'kelsi',
           'suzy',
           'jolene',
           'w',
           'ceola',
           'desire',
           'brook',
           'angelique',
           'jamar',
           'treena',
           'jacque',
           'denver',
           'phyliss',
           'angele',
           'bok',
           'lucile',
           'evelynn',
           'murray',
           'belkis',
           'teresita',
           'libbie',
           'eleonor',
           'ma',
           'ginger',
           'suzie',
           'maryetta',
           'elfriede',
           'christoper',
           'arent',
           'mitsue',
           'kathryne',
           'keitha',
           'christiana',
           'janelle',
           'nada',
           'mammie',
           'donita',
           'anette',
           'layne',
           'latarsha',
           'kaley',
           'who',
           'milda',
           'mao',
           'loyce',
           'lucrecia',
           'therefore',
           'retta',
           'thaddeus',
           'gilberto',
           'luis',
           'marcie',
           'angelo',
           'nikita',
           'ulysses',
           'under',
           'tatyana',
           'fe',
           'shirl',
           'anywhere',
           'dannie',
           'somehow',
           'elaine',
           'lasonya',
           'lynwood',
           'werent',
           'gregoria',
           'enola',
           'pamella',
           'anneliese',
           '5',
           'nieves',
           'tijuana',
           'lala',
           'eloy',
           'nancy',
           'due',
           'elliot',
           'venetta',
           'elizabet',
           'dia',
           'hazel',
           'meghan',
           '6',
           'kaylee',
           'zita',
           'ali',
           'molly',
           'sage',
           'isaiah',
           'brittny',
           'anh',
           'genevieve',
           'latonia',
           'shaun',
           'brittani',
           'jacquetta',
           'james',
           'ida',
           'lashay',
           'lydia',
           'nadia',
           'tanja',
           'nena',
           'bree',
           'frida',
           'adrienne',
           'janie',
           'toby',
           'arletta',
           'theola',
           'lauren',
           'joy',
           'gustavo',
           'patience',
           'had',
           'judith',
           'darcey',
           'regena',
           'sherril',
           'fay',
           'mariela',
           'carmen',
           'grover',
           'tawana',
           'whereby',
           'jeanice',
           'jackqueline',
           'carmela',
           'darell',
           'fabian',
           'leeanne',
           'natalie',
           'marjorie',
           'hallie',
           'halina',
           'raelene',
           'sophia',
           'johnathan',
           'charlesetta',
           'have',
           'dagny',
           'johnsie',
           'keli',
           'long',
           'jacalyn',
           'lin',
           'alfred',
           'aurore',
           'millie',
           'niki',
           'annalee',
           'act',
           'kali',
           'grady',
           'marcia',
           'cathie',
           'emeline',
           'maddie',
           'hundred',
           'shonda',
           'vivien',
           'ella',
           'barbra',
           'elicia',
           'aldo',
           'tamara',
           'olen',
           'rubye',
           'neda',
           'lida',
           'mozell',
           'jose',
           'mellissa',
           'does',
           'ara',
           'annika',
           'eryn',
           'ashli',
           'grisel',
           'cliff',
           'mei',
           'sylvia',
           'hulda',
           'dallas',
           'trevor',
           'elfrieda',
           'enedina',
           'leena',
           'nola',
           'floy',
           'iris',
           'magaret',
           'sometime',
           'arlen',
           'lana',
           'iliana',
           'lila',
           'shaunta',
           'bernard',
           'luther',
           'deb',
           'kiana',
           'towanda',
           'evangeline',
           'charline',
           'ie',
           'patrick',
           'shelba',
           'peter',
           'kristal',
           'arnoldo',
           'myron',
           'jerica',
           'alejandro',
           'adam',
           'hector',
           'bruna',
           'elvina',
           'glenda',
           'dottie',
           'penny',
           'ileen',
           'deandre',
           'cecile',
           'karena',
           'opal',
           'jospeh',
           'elmira',
           'deneen',
           'tangela',
           'laurette',
           'angela',
           'chieko',
           'trista',
           'ha',
           'each',
           'julieta',
           'robbi',
           'maple',
           'hisako',
           'eva',
           'wenona',
           'miyoko',
           'edith',
           'dagmar',
           'xavier',
           'lakiesha',
           'shemeka',
           'lonny',
           'lurline',
           'aleshia',
           'vikki',
           'ashleigh',
           'cornelius',
           'bulah',
           'quyen',
           'again',
           'lovetta',
           'matt',
           'except',
           'angel',
           'eugene',
           'sherri',
           'ebonie',
           'pa',
           'malika',
           'chester',
           'douglas',
           'charlyn',
           'ardelle',
           'did',
           'cruz',
           'everything',
           'left',
           'wouldnt',
           'zana',
           'bo',
           'letisha',
           'already',
           'carl',
           'aleen',
           'anna',
           'whither',
           'alethea',
           'jenette',
           'often',
           'corie',
           'albina',
           'always',
           'nella',
           'kandra',
           'well',
           'rolf',
           'vernita',
           'jaimie',
           'rufus',
           'since',
           'rosamond',
           'erlinda',
           'penni',
           'hai',
           'malissa',
           'domingo',
           'evelia',
           'herself',
           'christia',
           'dusti',
           'vince',
           'barbera',
           'wheres',
           'yuko',
           'calvin',
           'manuel',
           'sean',
           'maybe',
           'marleen',
           'paulina',
           'boyce',
           'irena',
           'adj',
           'santa',
           'donnie',
           'an',
           'shu',
           'carolann',
           'teofila',
           'allyn',
           'gennie',
           'jeneva',
           'proud',
           'stefani',
           'hyo',
           'been',
           'ned',
           'even',
           'kaci',
           'duncan',
           'other',
           'gay',
           'youve',
           'elden',
           'angelita',
           'oda',
           'weldon',
           'heriberto',
           'estelle',
           'genevie',
           'aileen',
           'laree',
           'darcy',
           'besides',
           'dinorah',
           'maryland',
           'livia',
           'marianna',
           'alane',
           'logan',
           'denise',
           'anything',
           'caitlyn',
           'shantae',
           'dorine',
           'natacha',
           'gil',
           'lara',
           'jennifer',
           'daniel',
           'marvin',
           'shaunte',
           'alysha',
           'ranee',
           'jacqueline',
           'former',
           'bobbi',
           'ciara',
           'noel',
           'tinisha',
           'suzann',
           'macy',
           'jenae',
           'latrice',
           'adan',
           'garth',
           'myrtle',
           'monique',
           'virgina',
           'elvis',
           'cleveland',
           'flor',
           'tiffani',
           'lura',
           'williams',
           'nestor',
           'shirely',
           'laquanda',
           'talia',
           'herma',
           'cassandra',
           'horacio',
           'leonore',
           'beforehand',
           'dionne',
           'victor',
           'eliz',
           'roma',
           'move',
           'leighann',
           'demetrius',
           'cathy',
           'myong',
           'connie',
           'jed',
           'ellamae',
           'reena',
           'vanetta',
           'brittney',
           'mitchel',
           'francoise',
           'fritz',
           'elva',
           'germaine',
           'mose',
           'basilia',
           'adrien',
           'ardis',
           'ingrid',
           'carson',
           'gaylord',
           'magdalen',
           'also',
           'bula',
           'dayna',
           'sheldon',
           'brandy',

In [7]:
corpus_path = '../docs/NYT-Obituaries/'
vectorizer = CountVectorizer(input='filename', encoding='utf8', stop_words = new_stopwords, min_df=20, dtype='float64')

### Make list of filepaths

CountVectorizer builds a dtm from a list of filepaths.

In [8]:
corpus = []
for title in obit_titles:
    filename = title + ".txt"
    corpus.append(corpus_path + filename)
dtm = vectorizer.fit_transform(corpus)

### Get feature names and set as column titles

The columns store word counts. We want to name the columns with the words stored in each, and to transform the dtm into a pandas dataframe, as follows:

In [12]:
vocab = vectorizer.get_feature_names()
matrix = dtm.toarray()
df = DataFrame(matrix, columns=vocab)
print('df shape is: ' + str(df.shape))

df shape is: (378, 2985)

Our dataframe has 378 rows, one for each document, or obituary, and 2985 columns, one for each word that's not in stopwords and appears at least 20 times in the corpus.

## Import metadata

In [13]:
meta = pd.read_csv("../docs/NYT-Obituaries.csv", encoding = 'utf-8')
meta

,title,gender,obit,date
0,1945-Adolf-Hitler,0,Hitler Fought Way to Power Unique in Modern Hi...,1945.0
1,1915-F-W-Taylor,0,"F. W. Taylor, Expert in Efficiency, Dies BY TH...",1915.0
2,1975-Chiang-Kai-shek,0,The Life of Chiang Kai-shek: A Leader Who Was ...,1975.0
3,1984-Ethel-Merman,1,"Ethel Merman, Queen of Musicals, Dies at 76 By...",1984.0
4,1953-Jim-Thorpe,0,Jim Thorpe Is Dead On West Coast at 64 Special...,1953.0
...,...,...,...,...
373,1987-Andres-Segovie,0,Andres Segovie Is Dead at 94; His Crusade Elev...,1987.0
374,1987-Rita-Hayworth,1,"Rita Hayworth, Movie Legend, Dies By ALBIN KRE...",1987.0
375,1993-William-Golding,0,"June 20, 1993 William Golding Is Dead at 81; ...",1993.0
376,1932-Florenz-Ziegfeld,1,Florenz Ziegfeld Dies in Hollywood After Long ...,1932.0
377,1938-Constantin-Stanislavsky,0,Stanislavsky Dies in Moscow At 75 By THE ED PR...,1938.0

In [14]:
meta = meta.rename(columns={'title': 'obit_title'})
meta

,obit_title,gender,obit,date
0,1945-Adolf-Hitler,0,Hitler Fought Way to Power Unique in Modern Hi...,1945.0
1,1915-F-W-Taylor,0,"F. W. Taylor, Expert in Efficiency, Dies BY TH...",1915.0
2,1975-Chiang-Kai-shek,0,The Life of Chiang Kai-shek: A Leader Who Was ...,1975.0
3,1984-Ethel-Merman,1,"Ethel Merman, Queen of Musicals, Dies at 76 By...",1984.0
4,1953-Jim-Thorpe,0,Jim Thorpe Is Dead On West Coast at 64 Special...,1953.0
...,...,...,...,...
373,1987-Andres-Segovie,0,Andres Segovie Is Dead at 94; His Crusade Elev...,1987.0
374,1987-Rita-Hayworth,1,"Rita Hayworth, Movie Legend, Dies By ALBIN KRE...",1987.0
375,1993-William-Golding,0,"June 20, 1993 William Golding Is Dead at 81; ...",1993.0
376,1932-Florenz-Ziegfeld,1,Florenz Ziegfeld Dies in Hollywood After Long ...,1932.0
377,1938-Constantin-Stanislavsky,0,Stanislavsky Dies in Moscow At 75 By THE ED PR...,1938.0

In [15]:
meta = meta[["obit_title", "gender", "date"]]
meta

                       obit_title  gender    date
0               1945-Adolf-Hitler       0  1945.0
1                 1915-F-W-Taylor       0  1915.0
2            1975-Chiang-Kai-shek       0  1975.0
3               1984-Ethel-Merman       1  1984.0
4                 1953-Jim-Thorpe       0  1953.0
..                            ...     ...     ...
373           1987-Andres-Segovie       0  1987.0
374            1987-Rita-Hayworth       1  1987.0
375          1993-William-Golding       0  1993.0
376         1932-Florenz-Ziegfeld       1  1932.0
377  1938-Constantin-Stanislavsky       0  1938.0

[378 rows x 3 columns]

Our metadata is stored as a pandas dataframe with a row for each obituary and three columns: title, gender, and year.

## Concatenate metadata and doc-term dataframe

In [16]:
df_concat = pd.concat([meta, df], axis = 1)

In [18]:
df_concat

,obit_title,gender,date,000,10,100,11,12,13,14,...,wrote,yale,year,years,yellow,yesterday,york,younger,youngest,youth
0,1945-Adolf-Hitler,0,1945.0,21.0,1.0,0.0,2.0,3.0,4.0,3.0,...,3.0,0.0,11.0,19.0,0.0,0.0,1.0,1.0,0.0,9.0
1,1915-F-W-Taylor,0,1915.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
2,1975-Chiang-Kai-shek,0,1975.0,3.0,3.0,1.0,1.0,0.0,0.0,0.0,...,6.0,0.0,3.0,14.0,0.0,0.0,1.0,2.0,1.0,1.0
3,1984-Ethel-Merman,1,1984.0,0.0,1.0,0.0,1.0,0.0,1.0,2.0,...,0.0,0.0,3.0,5.0,0.0,2.0,5.0,0.0,0.0,0.0
4,1953-Jim-Thorpe,0,1953.0,2.0,3.0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,6.0,1.0,0.0,0.0,4.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
373,1987-Andres-Segovie,0,1987.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,2.0,0.0,3.0,14.0,0.0,0.0,7.0,0.0,0.0,0.0
374,1987-Rita-Hayworth,1,1987.0,0.0,2.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,8.0,0.0,1.0,2.0,0.0,0.0,0.0
375,1993-William-Golding,0,1993.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,4.0,0.0,1.0,0.0,0.0,0.0,1.0
376,1932-Florenz-Ziegfeld,1,1932.0,9.0,3.0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,4.0,6.0,0.0,0.0,2.0,2.0,0.0,0.0
377,1938-Constantin-Stanislavsky,0,1938.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0

## Equalize numbers of men and women

We want our dataframe to have equal numbers of men and women. How many women are there? Women are counted as 1 and men as 0, so if we sum the gender column, we'll have the number of women:

In [20]:
# count the number of women
#df_concat[df_concat["gender"]==1].count()
df_concat["gender"].sum()

93

Then we separate men and women into two dataframes and take a random sample of 93 obituaries about men.

In [24]:
# create a dataframe with just the men
df_men = df_concat[df_concat["gender"]==0]
df_men

,obit_title,gender,date,000,10,100,11,12,13,14,...,wrote,yale,year,years,yellow,yesterday,york,younger,youngest,youth
0,1945-Adolf-Hitler,0,1945.0,21.0,1.0,0.0,2.0,3.0,4.0,3.0,...,3.0,0.0,11.0,19.0,0.0,0.0,1.0,1.0,0.0,9.0
1,1915-F-W-Taylor,0,1915.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
2,1975-Chiang-Kai-shek,0,1975.0,3.0,3.0,1.0,1.0,0.0,0.0,0.0,...,6.0,0.0,3.0,14.0,0.0,0.0,1.0,2.0,1.0,1.0
4,1953-Jim-Thorpe,0,1953.0,2.0,3.0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,6.0,1.0,0.0,0.0,4.0,0.0,0.0,0.0
8,1959-Cecil-De-Mille,0,1959.0,11.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0.0,0.0,3.0,5.0,0.0,0.0,2.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
371,1945-Jerome-Kern,0,1945.0,2.0,1.0,1.0,1.0,1.0,0.0,0.0,...,3.0,0.0,0.0,3.0,0.0,1.0,4.0,0.0,0.0,0.0
372,1991-Frank-Capra,0,1991.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,2.0,0.0,2.0,4.0,0.0,1.0,1.0,1.0,0.0,0.0
373,1987-Andres-Segovie,0,1987.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,2.0,0.0,3.0,14.0,0.0,0.0,7.0,0.0,0.0,0.0
375,1993-William-Golding,0,1993.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,4.0,0.0,1.0,0.0,0.0,0.0,1.0
377,1938-Constantin-Stanislavsky,0,1938.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0

In [25]:
# create a dataframe with just the women
df_women = df_concat[df_concat["gender"]==1]
df_women

,obit_title,gender,date,000,10,100,11,12,13,14,...,wrote,yale,year,years,yellow,yesterday,york,younger,youngest,youth
3,1984-Ethel-Merman,1,1984.0,0.0,1.0,0.0,1.0,0.0,1.0,2.0,...,0.0,0.0,3.0,5.0,0.0,2.0,5.0,0.0,0.0,0.0
5,1964-Nella-Larsen,1,1964.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,...,2.0,0.0,3.0,3.0,0.0,0.0,5.0,0.0,0.0,0.0
6,1955-Margaret-Abbott,1,1955.0,0.0,4.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,2.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
7,1984-Lillian-Hellman,1,1984.0,6.0,1.0,0.0,0.0,0.0,1.0,1.0,...,12.0,2.0,7.0,9.0,0.0,2.0,7.0,1.0,0.0,0.0
9,1928-Mabel-Craty,1,1928.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,2.0,0.0,1.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
353,1910-Florence-Nightingale,1,1854.0,3.0,0.0,0.0,0.0,1.0,0.0,1.0,...,2.0,0.0,2.0,7.0,0.0,1.0,1.0,0.0,0.0,1.0
355,1986-The-Challenger,1,1986.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,4.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
357,1998-Galina-Ulanova,1,1998.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,5.0,0.0,1.0,1.0,0.0,0.0,4.0,0.0,0.0,0.0
374,1987-Rita-Hayworth,1,1987.0,0.0,2.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,8.0,0.0,1.0,2.0,0.0,0.0,0.0
376,1932-Florenz-Ziegfeld,1,1932.0,9.0,3.0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,4.0,6.0,0.0,0.0,2.0,2.0,0.0,0.0

In [28]:
# take a random sample of 93 men
df_men = df_men.sample(93)
df_men

,obit_title,gender,date,000,10,100,11,12,13,14,...,wrote,yale,year,years,yellow,yesterday,york,younger,youngest,youth
320,1993-Albert-Sabin,0,1993.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,6.0,0.0,3.0,3.0,0.0,0.0,0.0
48,1941-Frank-Conrad,0,1941.0,0.0,0.0,0.0,2.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,1.0
265,1969-Coleman-Hawkins,0,1969.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,2.0,0.0,0.0,6.0,0.0,1.0,1.0,0.0,0.0,0.0
209,1933-Calvin-Coolidge,0,1933.0,6.0,1.0,0.0,1.0,0.0,0.0,0.0,...,8.0,0.0,7.0,14.0,0.0,0.0,8.0,0.0,0.0,0.0
224,1954-Henri-Matisse,0,1954.0,2.0,0.0,1.0,0.0,0.0,0.0,1.0,...,2.0,0.0,0.0,7.0,0.0,1.0,3.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184,1993-Arthur-Ashe,0,1993.0,0.0,2.0,0.0,0.0,1.0,1.0,1.0,...,0.0,0.0,7.0,5.0,0.0,1.0,5.0,0.0,0.0,1.0
129,1937-John-Rockefeller,0,1937.0,52.0,6.0,2.0,3.0,2.0,0.0,1.0,...,3.0,0.0,10.0,31.0,0.0,0.0,7.0,1.0,0.0,0.0
171,1931-Thomas-Edison,0,1931.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,3.0,2.0,0.0,1.0,0.0,0.0,0.0
95,1987-James-Baldwin,0,1987.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.0,0.0,0.0,5.0,0.0,4.0,4.0,0.0,0.0,1.0
329,1964-Herbert-Hoover,0,1964.0,1.0,1.0,0.0,2.0,0.0,0.0,0.0,...,1.0,0.0,0.0,5.0,0.0,2.0,2.0,0.0,0.0,0.0

We then concatenate the sampled men dataframe with the women dataframe and reset the index.

In [29]:
# concatenate sampled men df with women df
df_final = pd.concat([df_men, df_women])
df_final

,obit_title,gender,date,000,10,100,11,12,13,14,...,wrote,yale,year,years,yellow,yesterday,york,younger,youngest,youth
320,1993-Albert-Sabin,0,1993.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,6.0,0.0,3.0,3.0,0.0,0.0,0.0
48,1941-Frank-Conrad,0,1941.0,0.0,0.0,0.0,2.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,1.0
265,1969-Coleman-Hawkins,0,1969.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,2.0,0.0,0.0,6.0,0.0,1.0,1.0,0.0,0.0,0.0
209,1933-Calvin-Coolidge,0,1933.0,6.0,1.0,0.0,1.0,0.0,0.0,0.0,...,8.0,0.0,7.0,14.0,0.0,0.0,8.0,0.0,0.0,0.0
224,1954-Henri-Matisse,0,1954.0,2.0,0.0,1.0,0.0,0.0,0.0,1.0,...,2.0,0.0,0.0,7.0,0.0,1.0,3.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
353,1910-Florence-Nightingale,1,1854.0,3.0,0.0,0.0,0.0,1.0,0.0,1.0,...,2.0,0.0,2.0,7.0,0.0,1.0,1.0,0.0,0.0,1.0
355,1986-The-Challenger,1,1986.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,4.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
357,1998-Galina-Ulanova,1,1998.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,5.0,0.0,1.0,1.0,0.0,0.0,4.0,0.0,0.0,0.0
374,1987-Rita-Hayworth,1,1987.0,0.0,2.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,8.0,0.0,1.0,2.0,0.0,0.0,0.0
376,1932-Florenz-Ziegfeld,1,1932.0,9.0,3.0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,4.0,6.0,0.0,0.0,2.0,2.0,0.0,0.0

In [31]:
# reset the index
df_final = df_final.reset_index()
df_final

,level_0,index,obit_title,gender,date,000,10,100,11,12,...,wrote,yale,year,years,yellow,yesterday,york,younger,youngest,youth
0,0,320,1993-Albert-Sabin,0,1993.0,2.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,6.0,0.0,3.0,3.0,0.0,0.0,0.0
1,1,48,1941-Frank-Conrad,0,1941.0,0.0,0.0,0.0,2.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,1.0
2,2,265,1969-Coleman-Hawkins,0,1969.0,0.0,1.0,0.0,1.0,0.0,...,2.0,0.0,0.0,6.0,0.0,1.0,1.0,0.0,0.0,0.0
3,3,209,1933-Calvin-Coolidge,0,1933.0,6.0,1.0,0.0,1.0,0.0,...,8.0,0.0,7.0,14.0,0.0,0.0,8.0,0.0,0.0,0.0
4,4,224,1954-Henri-Matisse,0,1954.0,2.0,0.0,1.0,0.0,0.0,...,2.0,0.0,0.0,7.0,0.0,1.0,3.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181,181,353,1910-Florence-Nightingale,1,1854.0,3.0,0.0,0.0,0.0,1.0,...,2.0,0.0,2.0,7.0,0.0,1.0,1.0,0.0,0.0,1.0
182,182,355,1986-The-Challenger,1,1986.0,1.0,0.0,0.0,1.0,0.0,...,1.0,0.0,4.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
183,183,357,1998-Galina-Ulanova,1,1998.0,0.0,0.0,0.0,0.0,0.0,...,5.0,0.0,1.0,1.0,0.0,0.0,4.0,0.0,0.0,0.0
184,184,374,1987-Rita-Hayworth,1,1987.0,0.0,2.0,0.0,0.0,1.0,...,0.0,0.0,1.0,8.0,0.0,1.0,2.0,0.0,0.0,0.0
185,185,376,1932-Florenz-Ziegfeld,1,1932.0,9.0,3.0,1.0,1.0,0.0,...,0.0,0.0,4.0,6.0,0.0,0.0,2.0,2.0,0.0,0.0

We now have 186 rows: 93 men, 93 women.

In [ ]:
meta['gender'].sum()

In [ ]:
df_men = df_concat[df_concat['gender'] == 0]
df_women = df_concat[df_concat['gender'] == 1]
df_men = df_men.sample(n=93)

In [ ]:
df_final = pd.concat([df_men, df_women])
df_final

In [ ]:
df_final = df_final.reset_index()
df_final
df_final = df_final.drop(columns="index")
df_final

### Match meta and data dataframes with subset of df_final

We'll continue to use meta and df, so we need to ensure they match our subsetted df_final

In [ ]:
meta = df_final[["obit_title", "gender", "date"]]
meta

In [ ]:
df = df_final.loc[:,'000':]
df

## Let's run our classifier!

Once we have a dataframe with metadata and vocab counts we're ready to run our classifier!

### We add columns for probabilities and predicted class to our metadata

As we run the model, we are going to store its output with our metadata. This will allow us to easily examine the model's output.

In [ ]:
meta['PROBS'] = ''
meta['PREDICTED'] = ''

### Load model

We will use scikit-learn's `LogisticRegression` model. There are many other options for classifier models. Some are better for some tasks, other for others. LogisticRegression is standard for classifying literature. We set the penalty as l1 and the 'C' value as 1.0. If you decide to specialize in classification, you can explore further the implications of these arguments.

In [ ]:
model = LogisticRegression(penalty = 'l1', C = 1.0, solver='liblinear')

### Run the model!

We run the model in the following for-loop.

Classification models need classes: they need the texts grouped into different sets. Our metadata has built-in classes: gender. Men are stored as 0; women as 1. We could, if we wanted, create a new 0/1 class based on year.

Each iteration trains on all the titles except one, then predicts which class the excluded title belongs to. We'll call this leave-one-out classification. There are other ways of dividing training and testing sets, which we won't explore today.

The first four indented lines simply track our progress by printing index, title, and class. The next four lines exclude a single title, and set the training data and the test data.

The final six lines fit the model, calculate the probabilities and predicted class of the test case, and add that information to our metadata dataframe.

In [ ]:
for this_index in df_final.index.tolist():
    print(this_index) # keep track of where we are in the corpus
    title = meta.loc[meta.index[this_index], 'obit_title'] 
    CLASS = meta.loc[meta.index[this_index], 'gender']
    print(title, CLASS) 
    
    train_index_list = [index_ for index_ in df.index.tolist() if index_ != this_index] # exclude the title to be predicted
    X = df.loc[train_index_list] # the model trains on all the data except the excluded title row
    y = meta.loc[train_index_list, 'gender'] # the y row tells the model which class each title belongs to
    TEST_CASE = df.loc[[this_index]]

    model.fit(X,y) # fit the model
    prediction = model.predict_proba(TEST_CASE) # calculate probability of test case
    predicted = model.predict(TEST_CASE) # calculate predicted class of test case
    meta.at[this_index, 'PREDICTED'] = predicted # add predicted class to metadata
    meta.at[this_index, 'PROBS'] = str(prediction) # add probabilities to metadata
    print('Class is: ' + str(CLASS) + '\n' + 'Prediction is: ' + str(predicted) + ' ' + str(prediction) + '\n')

How cool is this! For each obituary, we see who it's about, that person's gender (0 or 1), and which gender the model thinks it's about, by which probabilities. 

What can you glean by glancing through?

ANSWER HERE
* *
* *
* *
* *

## Results

Remember, we've stored our results in our metadata dataframe. Let's take a look!

In [ ]:
meta

There's lots to look at here. We could explore probabilities: which obituaries is the model most sure about? Which are closest to 50-50? Which does it get most right and most wrong? Is there a pattern to misclassified obituaries?

For now, we just want to calculate its accuracy. Let's get rid of those brackets in the PREDICTED column.

In [ ]:
meta = meta.replace([0], 0)
meta = meta.replace([1], 1)
meta

### Result column

Now we can add a 'RESULT' column that is the result of subtracting the predicted gender from the actual gender.

0 means the model was correct.
-1 means the model mistook a man for a woman.
1 means the model mistook a woman for a man.

In [ ]:
sum_column = meta['gender'] - meta['PREDICTED']
meta['RESULT'] = sum_column
meta

Let's look at the accurate guesses.

In [ ]:
meta = meta[meta['RESULT'] == 0]
meta

## Accuracy

How many did the model get correct?

We can calculate its accuracy by dividing the correct number by the total.

In [ ]:
# divide here

Pretty good rate! At random, the model should guess correctly 50% of the time. It does **much** better than that!

In the next lesson, we'll explore _how_ the model made its calculations by learning which words matter.

## BONUS

If you want to explore further, divide the obituaries by year rather than gender. You'll need to do some data clearning and some manipulation of pandas to make it work. Can you figure it out?

If you're feeling REALLY ambitious, you can use this notebook and the next one to run classification over your own data. All you need is a text corpus with binary metadata (that is, metadata that can be divided into two classes). Classification works best if you have at least around eighty texts of each class, so our lyrics corpus is too small (though you could try and see what happens.